# AI Static Code Vulnerability Scanner - Auto-generated Setup Script
# Run with: powershell -ExecutionPolicy Bypass -File SETUP.ps1

Write-Host "Building AI Static Vulnerability Scanner..." -ForegroundColor Cyan

$root = "ai-static-scanner"

# Create all directories
New-Item -ItemType Directory -Force -Path ($root + "/.github") | Out-Null
New-Item -ItemType Directory -Force -Path ($root + "/.github/workflows") | Out-Null
New-Item -ItemType Directory -Force -Path ($root + "/backend") | Out-Null
New-Item -ItemType Directory -Force -Path ($root + "/backend/app") | Out-Null
New-Item -ItemType Directory -Force -Path ($root + "/backend/app/ai") | Out-Null
New-Item -ItemType Directory -Force -Path ($root + "/backend/app/api") | Out-Null
New-Item -ItemType Directory -Force -Path ($root + "/backend/app/api/routes") | Out-Null
New-Item -ItemType Directory -Force -Path ($root + "/backend/app/core") | Out-Null
New-Item -ItemType Directory -Force -Path ($root + "/backend/app/models") | Out-Null
New-Item -ItemType Directory -Force -Path ($root + "/backend/app/scanners") | Out-Null
New-Item -ItemType Directory -Force -Path ($root + "/backend/app/scanners/rules") | Out-Null
New-Item -ItemType Directory -Force -Path ($root + "/backend/app/schemas") | Out-Null
New-Item -ItemType Directory -Force -Path ($root + "/backend/app/services") | Out-Null
New-Item -ItemType Directory -Force -Path ($root + "/backend/app/workers") | Out-Null
New-Item -ItemType Directory -Force -Path ($root + "/frontend") | Out-Null
New-Item -ItemType Directory -Force -Path ($root + "/frontend/src") | Out-Null
New-Item -ItemType Directory -Force -Path ($root + "/frontend/src/components") | Out-Null
New-Item -ItemType Directory -Force -Path ($root + "/frontend/src/context") | Out-Null
New-Item -ItemType Directory -Force -Path ($root + "/frontend/src/pages") | Out-Null
New-Item -ItemType Directory -Force -Path ($root + "/frontend/src/services") | Out-Null

# ---- .github/workflows/ci.yml
$b64 = "bmFtZTogQ0kKb246CiAgcHVzaDoKICAgIGJyYW5jaGVzOiBbbWFpbl0KICBwdWxsX3JlcXVlc3Q6CiAgICBicmFuY2hlczogW21haW5dCgpqb2JzOgogIHRlc3Q6CiAgICBydW5zLW9uOiB1YnVudHUtbGF0ZXN0CiAgICBzdGVwczoKICAgICAgLSB1c2VzOiBhY3Rpb25zL2NoZWNrb3V0QHY0CiAgICAgIC0gdXNlczogYWN0aW9ucy9zZXR1cC1weXRob25AdjUKICAgICAgICB3aXRoOgogICAgICAgICAgcHl0aG9uLXZlcnNpb246ICIzLjExIgogICAgICAtIG5hbWU6IEluc3RhbGwgZGVwcwogICAgICAgIHJ1bjogY2QgYmFja2VuZCAmJiBwaXAgaW5zdGFsbCAtciByZXF1aXJlbWVudHMudHh0CiAgICAgIC0gbmFtZTogU21va2UgdGVzdAogICAgICAgIHJ1bjogfAogICAgICAgICAgY2QgYmFja2VuZAogICAgICAgICAgcHl0aG9uIC1jICIKICAgICAgICAgIGltcG9ydCBhc3QsIHN5cwogICAgICAgICAgc3lzLnBhdGguaW5zZXJ0KDAsICcuJykKICAgICAgICAgIGZyb20gYXBwLnNjYW5uZXJzLnJ1bGVzLnNxbF9pbmplY3Rpb24gaW1wb3J0IGRldGVjdF9zcWxfaW5qZWN0aW9uCiAgICAgICAgICBmcm9tIGFwcC5zY2FubmVycy5ydWxlcy5oYXJkY29kZWRfc2VjcmV0cyBpbXBvcnQgZGV0ZWN0X2hhcmRjb2RlZF9zZWNyZXRzCiAgICAgICAgICBwcmludCgnUnVsZXMgaW1wb3J0ZWQgT0snKQogICAgICAgICAgIgogICAgICAtIG5hbWU6IERvY2tlciBidWlsZAogICAgICAgIHJ1bjogZG9ja2VyIGNvbXBvc2UgYnVpbGQK"
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/.github/workflows/ci.yml")),
    [System.Convert]::FromBase64String($b64)
)

# ---- README.md
$b64 = "IyBBSSBTdGF0aWMgQ29kZSBWdWxuZXJhYmlsaXR5IFNjYW5uZXIKClByb2R1Y3Rpb24tZ3JhZGUgU0FTVCBwbGF0Zm9ybSB1c2luZyBBU1QgYW5hbHlzaXMgKyBBSSBleHBsYW5hdGlvbnMuCgojIyBRdWljayBTdGFydAoKMS4gRWRpdCBgYmFja2VuZC8uZW52YCAtIGFkZCB5b3VyIEFQSSBrZXk6CiAgIC0gYE9QRU5BSV9BUElfS0VZPXNrLS4uLmAgIE9SCiAgIC0gYEFOVEhST1BJQ19BUElfS0VZPXNrLWFudC0uLi5gCgoyLiBMYXVuY2g6CiAgIGBgYAogICBkb2NrZXIgY29tcG9zZSB1cCAtLWJ1aWxkCiAgIGBgYAoKMy4gT3BlbjoKICAgLSBGcm9udGVuZDogaHR0cDovL2xvY2FsaG9zdDozMDAwCiAgIC0gQVBJIERvY3M6ICBodHRwOi8vbG9jYWxob3N0OjgwMDAvZG9jcwoKIyMgV2hhdCBJdCBEZXRlY3RzCi0gU1FMIEluamVjdGlvbiAoQTAzKQotIENvbW1hbmQgSW5qZWN0aW9uIChBMDMpCi0gWFNTIChBMDMpCi0gSGFyZGNvZGVkIFNlY3JldHMgKEEwMikKLSBJbnNlY3VyZSBEZXNlcmlhbGl6YXRpb24gKEEwOCkKLSBQYXRoIFRyYXZlcnNhbCAoQTAxKQo="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/README.md")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/.env
$b64 = "REFUQUJBU0VfVVJMPXBvc3RncmVzcWw6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0BkYjo1NDMyL3NjYW5uZXIKU0VDUkVUX0tFWT1jaGFuZ2UtdGhpcy10by1hLWxvbmctcmFuZG9tLXNlY3JldC1rZXktaW4tcHJvZHVjdGlvbgpBTEdPUklUSE09SFMyNTYKQUNDRVNTX1RPS0VOX0VYUElSRV9NSU5VVEVTPTYwCgpPUEVOQUlfQVBJX0tFWT1zay15b3VyLW9wZW5haS1rZXktaGVyZQpBTlRIUk9QSUNfQVBJX0tFWT1zay1hbnQteW91ci1hbnRocm9waWMta2V5LWhlcmUKR0lUSFVCX1RPS0VOPWdocF95b3VyLWdpdGh1Yi1wYXQtaGVyZQpSRURJU19VUkw9cmVkaXM6Ly9yZWRpczo2Mzc5LzAK"
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/.env")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/Dockerfile
$b64 = "RlJPTSBweXRob246My4xMS1zbGltClJVTiBhcHQtZ2V0IHVwZGF0ZSAmJiBhcHQtZ2V0IGluc3RhbGwgLXkgLS1uby1pbnN0YWxsLXJlY29tbWVuZHMgZ2l0IGxpYnBxLWRldiBnY2MgJiYgcm0gLXJmIC92YXIvbGliL2FwdC9saXN0cy8qCldPUktESVIgL2FwcApDT1BZIHJlcXVpcmVtZW50cy50eHQgLgpSVU4gcGlwIGluc3RhbGwgLS1uby1jYWNoZS1kaXIgLXIgcmVxdWlyZW1lbnRzLnR4dApDT1BZIC4gLgpDTUQgWyJ1dmljb3JuIiwgImFwcC5tYWluOmFwcCIsICItLWhvc3QiLCAiMC4wLjAuMCIsICItLXBvcnQiLCAiODAwMCIsICItLXJlbG9hZCJdCg=="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/Dockerfile")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/__init__.py
$b64 = ""
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/__init__.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/ai/__init__.py
$b64 = ""
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/ai/__init__.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/ai/llm_client.py
$b64 = "ZnJvbSBhcHAuY29yZS5jb25maWcgaW1wb3J0IHNldHRpbmdzCmZyb20gYXBwLmFpLnByb21wdHMgaW1wb3J0IFNZU1RFTV9QUk9NUFQsIGJ1aWxkX3Byb21wdAoKZGVmIGdlbmVyYXRlX2FpX2V4cGxhbmF0aW9uKGZpbmRpbmc6IGRpY3QpIC0+IHN0cjoKICAgIHByb21wdCA9IGJ1aWxkX3Byb21wdChmaW5kaW5nKQoKICAgIGlmIHNldHRpbmdzLk9QRU5BSV9BUElfS0VZIGFuZCBub3Qgc2V0dGluZ3MuT1BFTkFJX0FQSV9LRVkuc3RhcnRzd2l0aCgic2steW91ciIpOgogICAgICAgIHRyeToKICAgICAgICAgICAgZnJvbSBvcGVuYWkgaW1wb3J0IE9wZW5BSQogICAgICAgICAgICBjbGllbnQgPSBPcGVuQUkoYXBpX2tleT1zZXR0aW5ncy5PUEVOQUlfQVBJX0tFWSkKICAgICAgICAgICAgcmVzcCA9IGNsaWVudC5jaGF0LmNvbXBsZXRpb25zLmNyZWF0ZSgKICAgICAgICAgICAgICAgIG1vZGVsPSJncHQtNG8tbWluaSIsCiAgICAgICAgICAgICAgICBtZXNzYWdlcz1bCiAgICAgICAgICAgICAgICAgICAgeyJyb2xlIjogInN5c3RlbSIsICJjb250ZW50IjogU1lTVEVNX1BST01QVH0sCiAgICAgICAgICAgICAgICAgICAgeyJyb2xlIjogInVzZXIiLCAiY29udGVudCI6IHByb21wdH0sCiAgICAgICAgICAgICAgICBdLAogICAgICAgICAgICAgICAgbWF4X3Rva2Vucz02MDAsCiAgICAgICAgICAgICkKICAgICAgICAgICAgcmV0dXJuIHJlc3AuY2hvaWNlc1swXS5tZXNzYWdlLmNvbnRlbnQKICAgICAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgICAgIHByaW50KGYiW09wZW5BSV0gZXJyb3I6IHtlfSIpCgogICAgaWYgc2V0dGluZ3MuQU5USFJPUElDX0FQSV9LRVkgYW5kIG5vdCBzZXR0aW5ncy5BTlRIUk9QSUNfQVBJX0tFWS5zdGFydHN3aXRoKCJzay1hbnQteW91ciIpOgogICAgICAgIHRyeToKICAgICAgICAgICAgaW1wb3J0IGFudGhyb3BpYwogICAgICAgICAgICBjbGllbnQgPSBhbnRocm9waWMuQW50aHJvcGljKGFwaV9rZXk9c2V0dGluZ3MuQU5USFJPUElDX0FQSV9LRVkpCiAgICAgICAgICAgIHJlc3AgPSBjbGllbnQubWVzc2FnZXMuY3JlYXRlKAogICAgICAgICAgICAgICAgbW9kZWw9ImNsYXVkZS1zb25uZXQtNC0yMDI1MDUxNCIsCiAgICAgICAgICAgICAgICBtYXhfdG9rZW5zPTYwMCwKICAgICAgICAgICAgICAgIHN5c3RlbT1TWVNURU1fUFJPTVBULAogICAgICAgICAgICAgICAgbWVzc2FnZXM9W3sicm9sZSI6ICJ1c2VyIiwgImNvbnRlbnQiOiBwcm9tcHR9XSwKICAgICAgICAgICAgKQogICAgICAgICAgICByZXR1cm4gcmVzcC5jb250ZW50WzBdLnRleHQKICAgICAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgICAgIHByaW50KGYiW0FudGhyb3BpY10gZXJyb3I6IHtlfSIpCgogICAgcmV0dXJuICgKICAgICAgICBmIioqe2ZpbmRpbmdbJ2NhdGVnb3J5J119KiogYXQgbGluZSB7ZmluZGluZy5nZXQoJ2xpbmUnLCAnPycpfS5cblxuIgogICAgICAgIGYie2ZpbmRpbmdbJ2Rlc2NyaXB0aW9uJ119XG5cbiIKICAgICAgICBmIk9XQVNQOiB7ZmluZGluZy5nZXQoJ293YXNwJywgJ1NlZSBPV0FTUCBUb3AgMTAnKX1cblxuIgogICAgICAgICJBZGQgT1BFTkFJX0FQSV9LRVkgb3IgQU5USFJPUElDX0FQSV9LRVkgaW4gYmFja2VuZC8uZW52IGZvciBBSSBleHBsYW5hdGlvbnMuIgogICAgKQo="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/ai/llm_client.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/ai/prompts.py
$b64 = "U1lTVEVNX1BST01QVCA9ICgKICAgICJZb3UgYXJlIGEgc2VuaW9yIGFwcGxpY2F0aW9uIHNlY3VyaXR5IGVuZ2luZWVyLiAiCiAgICAiRm9yIHRoZSBnaXZlbiB2dWxuZXJhYmlsaXR5IHByb3ZpZGU6ICIKICAgICIxKSBXaGF0IEl0IElzLCAyKSBBdHRhY2sgU2NlbmFyaW8sIDMpIE9XQVNQIE1hcHBpbmcsICIKICAgICI0KSBSZW1lZGlhdGlvbiBzdGVwcywgNSkgU2VjdXJlIENvZGUgRXhhbXBsZS4gIgogICAgIkJlIGNvbmNpc2UgKHVuZGVyIDMwMCB3b3JkcykgYW5kIGRldmVsb3Blci1mcmllbmRseS4iCikKCmRlZiBidWlsZF9wcm9tcHQoZmluZGluZzogZGljdCkgLT4gc3RyOgogICAgcmV0dXJuICgKICAgICAgICBmIkZpbGU6IHtmaW5kaW5nLmdldCgnZmlsZScsICd1bmtub3duJyl9XG4iCiAgICAgICAgZiJMaW5lOiB7ZmluZGluZy5nZXQoJ2xpbmUnLCAnPycpfVxuIgogICAgICAgIGYiQ2F0ZWdvcnk6IHtmaW5kaW5nWydjYXRlZ29yeSddfVxuIgogICAgICAgIGYiU2V2ZXJpdHk6IHtmaW5kaW5nWydzZXZlcml0eSddfVxuIgogICAgICAgIGYiRGVzY3JpcHRpb246IHtmaW5kaW5nWydkZXNjcmlwdGlvbiddfVxuIgogICAgKQo="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/ai/prompts.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/api/__init__.py
$b64 = ""
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/api/__init__.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/api/deps.py
$b64 = "ZnJvbSBhcHAuY29yZS5zZWN1cml0eSBpbXBvcnQgZ2V0X2N1cnJlbnRfdXNlcgpmcm9tIGFwcC5jb3JlLmRhdGFiYXNlIGltcG9ydCBnZXRfZGIK"
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/api/deps.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/api/routes/__init__.py
$b64 = ""
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/api/routes/__init__.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/api/routes/auth.py
$b64 = "ZnJvbSBmYXN0YXBpIGltcG9ydCBBUElSb3V0ZXIsIERlcGVuZHMKZnJvbSBmYXN0YXBpLnNlY3VyaXR5IGltcG9ydCBPQXV0aDJQYXNzd29yZFJlcXVlc3RGb3JtCmZyb20gc3FsYWxjaGVteS5vcm0gaW1wb3J0IFNlc3Npb24KZnJvbSBhcHAuY29yZS5kYXRhYmFzZSBpbXBvcnQgZ2V0X2RiCmZyb20gYXBwLnNjaGVtYXMuYXV0aCBpbXBvcnQgUmVnaXN0ZXJSZXF1ZXN0LCBMb2dpblJlc3BvbnNlCmZyb20gYXBwLnNlcnZpY2VzLmF1dGhfc2VydmljZSBpbXBvcnQgcmVnaXN0ZXJfdXNlciwgbG9naW5fdXNlcgoKcm91dGVyID0gQVBJUm91dGVyKHByZWZpeD0iL2F1dGgiLCB0YWdzPVsiYXV0aCJdKQoKQHJvdXRlci5wb3N0KCIvcmVnaXN0ZXIiLCBzdGF0dXNfY29kZT0yMDEpCmRlZiByZWdpc3RlcihyZXE6IFJlZ2lzdGVyUmVxdWVzdCwgZGI6IFNlc3Npb24gPSBEZXBlbmRzKGdldF9kYikpOgogICAgdXNlciA9IHJlZ2lzdGVyX3VzZXIocmVxLmVtYWlsLCByZXEucGFzc3dvcmQsIGRiKQogICAgcmV0dXJuIHsibWVzc2FnZSI6ICJSZWdpc3RlcmVkIHN1Y2Nlc3NmdWxseSIsICJ1c2VyX2lkIjogdXNlci5pZH0KCkByb3V0ZXIucG9zdCgiL2xvZ2luIiwgcmVzcG9uc2VfbW9kZWw9TG9naW5SZXNwb25zZSkKZGVmIGxvZ2luKGZvcm06IE9BdXRoMlBhc3N3b3JkUmVxdWVzdEZvcm0gPSBEZXBlbmRzKCksIGRiOiBTZXNzaW9uID0gRGVwZW5kcyhnZXRfZGIpKToKICAgIHJldHVybiBsb2dpbl91c2VyKGZvcm0udXNlcm5hbWUsIGZvcm0ucGFzc3dvcmQsIGRiKQo="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/api/routes/auth.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/api/routes/reports.py
$b64 = "ZnJvbSBmYXN0YXBpIGltcG9ydCBBUElSb3V0ZXIsIERlcGVuZHMsIEhUVFBFeGNlcHRpb24KZnJvbSBmYXN0YXBpLnJlc3BvbnNlcyBpbXBvcnQgUmVzcG9uc2UsIEpTT05SZXNwb25zZQpmcm9tIHNxbGFsY2hlbXkub3JtIGltcG9ydCBTZXNzaW9uCmZyb20gcmVwb3J0bGFiLmxpYi5wYWdlc2l6ZXMgaW1wb3J0IGxldHRlcgpmcm9tIHJlcG9ydGxhYi5saWIgaW1wb3J0IGNvbG9ycwpmcm9tIHJlcG9ydGxhYi5wbGF0eXB1cyBpbXBvcnQgU2ltcGxlRG9jVGVtcGxhdGUsIFBhcmFncmFwaCwgU3BhY2VyLCBUYWJsZSwgVGFibGVTdHlsZQpmcm9tIHJlcG9ydGxhYi5saWIuc3R5bGVzIGltcG9ydCBnZXRTYW1wbGVTdHlsZVNoZWV0CmZyb20gcmVwb3J0bGFiLmxpYi51bml0cyBpbXBvcnQgaW5jaApmcm9tIGlvIGltcG9ydCBCeXRlc0lPCmZyb20gYXBwLmNvcmUuZGF0YWJhc2UgaW1wb3J0IGdldF9kYgpmcm9tIGFwcC5jb3JlLnNlY3VyaXR5IGltcG9ydCBnZXRfY3VycmVudF91c2VyCmZyb20gYXBwLm1vZGVscy5zY2FuIGltcG9ydCBTY2FuCmZyb20gYXBwLm1vZGVscy51c2VyIGltcG9ydCBVc2VyCgpyb3V0ZXIgPSBBUElSb3V0ZXIocHJlZml4PSIvcmVwb3J0cyIsIHRhZ3M9WyJyZXBvcnRzIl0pCgpAcm91dGVyLmdldCgiL3tzY2FuX2lkfS9qc29uIikKZGVmIGV4cG9ydF9qc29uKHNjYW5faWQ6IGludCwgZGI6IFNlc3Npb24gPSBEZXBlbmRzKGdldF9kYiksCiAgICAgICAgICAgICAgICBjdXJyZW50X3VzZXI6IFVzZXIgPSBEZXBlbmRzKGdldF9jdXJyZW50X3VzZXIpKToKICAgIHNjYW4gPSBkYi5xdWVyeShTY2FuKS5maWx0ZXIoU2Nhbi5pZCA9PSBzY2FuX2lkLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgU2Nhbi51c2VyX2lkID09IGN1cnJlbnRfdXNlci5pZCkuZmlyc3QoKQogICAgaWYgbm90IHNjYW46CiAgICAgICAgcmFpc2UgSFRUUEV4Y2VwdGlvbig0MDQsICJTY2FuIG5vdCBmb3VuZCIpCiAgICByZXR1cm4gSlNPTlJlc3BvbnNlKHsKICAgICAgICAic2Nhbl9pZCI6IHNjYW4uaWQsICJyZXBvX3VybCI6IHNjYW4ucmVwb191cmwsICJzdGF0dXMiOiBzY2FuLnN0YXR1cywKICAgICAgICAiY3JlYXRlZF9hdCI6IHN0cihzY2FuLmNyZWF0ZWRfYXQpLAogICAgICAgICJ2dWxuZXJhYmlsaXRpZXMiOiBbCiAgICAgICAgICAgIHsiZmlsZSI6IHYuZmlsZSwgImxpbmUiOiB2LmxpbmUsICJjYXRlZ29yeSI6IHYuY2F0ZWdvcnksCiAgICAgICAgICAgICAic2V2ZXJpdHkiOiB2LnNldmVyaXR5LCAiZGVzY3JpcHRpb24iOiB2LmRlc2NyaXB0aW9uLAogICAgICAgICAgICAgIm93YXNwIjogdi5vd2FzcCwgImFpX2V4cGxhbmF0aW9uIjogdi5haV9leHBsYW5hdGlvbn0KICAgICAgICAgICAgZm9yIHYgaW4gc2Nhbi52dWxuZXJhYmlsaXRpZXMKICAgICAgICBdCiAgICB9KQoKQHJvdXRlci5nZXQoIi97c2Nhbl9pZH0vcGRmIikKZGVmIGV4cG9ydF9wZGYoc2Nhbl9pZDogaW50LCBkYjogU2Vzc2lvbiA9IERlcGVuZHMoZ2V0X2RiKSwKICAgICAgICAgICAgICAgY3VycmVudF91c2VyOiBVc2VyID0gRGVwZW5kcyhnZXRfY3VycmVudF91c2VyKSk6CiAgICBzY2FuID0gZGIucXVlcnkoU2NhbikuZmlsdGVyKFNjYW4uaWQgPT0gc2Nhbl9pZCwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIFNjYW4udXNlcl9pZCA9PSBjdXJyZW50X3VzZXIuaWQpLmZpcnN0KCkKICAgIGlmIG5vdCBzY2FuOgogICAgICAgIHJhaXNlIEhUVFBFeGNlcHRpb24oNDA0LCAiU2NhbiBub3QgZm91bmQiKQogICAgYnVmID0gQnl0ZXNJTygpCiAgICBkb2MgPSBTaW1wbGVEb2NUZW1wbGF0ZShidWYsIHBhZ2VzaXplPWxldHRlciwKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGxlZnRNYXJnaW49MC43NSppbmNoLCByaWdodE1hcmdpbj0wLjc1KmluY2gsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICB0b3BNYXJnaW49MC43NSppbmNoLCBib3R0b21NYXJnaW49MC43NSppbmNoKQogICAgc3R5bGVzID0gZ2V0U2FtcGxlU3R5bGVTaGVldCgpCiAgICBzdG9yeSAgPSBbCiAgICAgICAgUGFyYWdyYXBoKCJBSSBWdWxuZXJhYmlsaXR5IFNjYW5uZXIgUmVwb3J0Iiwgc3R5bGVzWyJUaXRsZSJdKSwKICAgICAgICBQYXJhZ3JhcGgoZiJSZXBvc2l0b3J5OiB7c2Nhbi5yZXBvX3VybH0iLCBzdHlsZXNbIk5vcm1hbCJdKSwKICAgICAgICBQYXJhZ3JhcGgoZiJTY2FuIElEOiB7c2Nhbi5pZH0gIFN0YXR1czoge3NjYW4uc3RhdHVzfSIsIHN0eWxlc1siTm9ybWFsIl0pLAogICAgICAgIFNwYWNlcigxLCAwLjIqaW5jaCksCiAgICBdCiAgICBpZiBub3Qgc2Nhbi52dWxuZXJhYmlsaXRpZXM6CiAgICAgICAgc3RvcnkuYXBwZW5kKFBhcmFncmFwaCgiTm8gdnVsbmVyYWJpbGl0aWVzIGRldGVjdGVkLiIsIHN0eWxlc1siTm9ybWFsIl0pKQogICAgZWxzZToKICAgICAgICBmb3IgdiBpbiBzY2FuLnZ1bG5lcmFiaWxpdGllczoKICAgICAgICAgICAgc3RvcnkuYXBwZW5kKFBhcmFncmFwaChmInt2LmNhdGVnb3J5fSAtIHt2LnNldmVyaXR5fSIsIHN0eWxlc1siSGVhZGluZzIiXSkpCiAgICAgICAgICAgIHQgPSBUYWJsZShbCiAgICAgICAgICAgICAgICBbIkZpbGUiLCB2LmZpbGUgb3IgIk4vQSJdLCBbIkxpbmUiLCBzdHIodi5saW5lIG9yICI/IildLAogICAgICAgICAgICAgICAgWyJPV0FTUCIsIHYub3dhc3Agb3IgIk4vQSJdLCBbIkRlc2NyaXB0aW9uIiwgdi5kZXNjcmlwdGlvbl0sCiAgICAgICAgICAgIF0sIGNvbFdpZHRocz1bMS4yKmluY2gsIDUuOCppbmNoXSkKICAgICAgICAgICAgdC5zZXRTdHlsZShUYWJsZVN0eWxlKFsKICAgICAgICAgICAgICAgICgiQkFDS0dST1VORCIsICgwLDApLCAoMCwtMSksIGNvbG9ycy5saWdodGdyZXkpLAogICAgICAgICAgICAgICAgKCJHUklEIiwgKDAsMCksICgtMSwtMSksIDAuNSwgY29sb3JzLmdyZXkpLAogICAgICAgICAgICAgICAgKCJWQUxJR04iLCAoMCwwKSwgKC0xLC0xKSwgIlRPUCIpLAogICAgICAgICAgICBdKSkKICAgICAgICAgICAgc3RvcnkuYXBwZW5kKHQpCiAgICAgICAgICAgIGlmIHYuYWlfZXhwbGFuYXRpb246CiAgICAgICAgICAgICAgICBzdG9yeS5hcHBlbmQoU3BhY2VyKDEsIDAuMSppbmNoKSkKICAgICAgICAgICAgICAgIHN0b3J5LmFwcGVuZChQYXJhZ3JhcGgoIkFJIEFuYWx5c2lzOiIsIHN0eWxlc1siSGVhZGluZzMiXSkpCiAgICAgICAgICAgICAgICBzdG9yeS5hcHBlbmQoUGFyYWdyYXBoKAogICAgICAgICAgICAgICAgICAgIHYuYWlfZXhwbGFuYXRpb24ucmVwbGFjZSgiXG4iLCAiPGJyLz4iKSwgc3R5bGVzWyJOb3JtYWwiXSkpCiAgICAgICAgICAgIHN0b3J5LmFwcGVuZChTcGFjZXIoMSwgMC4yNSppbmNoKSkKICAgIGRvYy5idWlsZChzdG9yeSkKICAgIGJ1Zi5zZWVrKDApCiAgICByZXR1cm4gUmVzcG9uc2UoYnVmLnJlYWQoKSwgbWVkaWFfdHlwZT0iYXBwbGljYXRpb24vcGRmIiwKICAgICAgICAgICAgICAgICAgICBoZWFkZXJzPXsiQ29udGVudC1EaXNwb3NpdGlvbiI6IGYiYXR0YWNobWVudDsgZmlsZW5hbWU9c2Nhbl97c2Nhbl9pZH0ucGRmIn0pCg=="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/api/routes/reports.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/api/routes/scan.py
$b64 = "ZnJvbSBmYXN0YXBpIGltcG9ydCBBUElSb3V0ZXIsIERlcGVuZHMsIEhUVFBFeGNlcHRpb24KZnJvbSBzcWxhbGNoZW15Lm9ybSBpbXBvcnQgU2Vzc2lvbgpmcm9tIHR5cGluZyBpbXBvcnQgTGlzdApmcm9tIGFwcC5jb3JlLmRhdGFiYXNlIGltcG9ydCBnZXRfZGIKZnJvbSBhcHAuY29yZS5zZWN1cml0eSBpbXBvcnQgZ2V0X2N1cnJlbnRfdXNlcgpmcm9tIGFwcC5tb2RlbHMuc2NhbiBpbXBvcnQgU2Nhbgpmcm9tIGFwcC5tb2RlbHMudXNlciBpbXBvcnQgVXNlcgpmcm9tIGFwcC5zY2hlbWFzLnNjYW4gaW1wb3J0IFNjYW5SZXF1ZXN0LCBTY2FuT3V0CmZyb20gYXBwLndvcmtlcnMuc2Nhbl90YXNrcyBpbXBvcnQgcnVuX3NjYW5fdGFzawoKcm91dGVyID0gQVBJUm91dGVyKHByZWZpeD0iL3NjYW4iLCB0YWdzPVsic2NhbiJdKQoKQHJvdXRlci5wb3N0KCIiLCByZXNwb25zZV9tb2RlbD1TY2FuT3V0LCBzdGF0dXNfY29kZT0yMDIpCmRlZiBzdGFydF9zY2FuKHJlcTogU2NhblJlcXVlc3QsIGRiOiBTZXNzaW9uID0gRGVwZW5kcyhnZXRfZGIpLAogICAgICAgICAgICAgICBjdXJyZW50X3VzZXI6IFVzZXIgPSBEZXBlbmRzKGdldF9jdXJyZW50X3VzZXIpKToKICAgIHNjYW4gPSBTY2FuKHJlcG9fdXJsPXJlcS5yZXBvX3VybCwgc3RhdHVzPSJxdWV1ZWQiLCB1c2VyX2lkPWN1cnJlbnRfdXNlci5pZCkKICAgIGRiLmFkZChzY2FuKQogICAgZGIuY29tbWl0KCkKICAgIGRiLnJlZnJlc2goc2NhbikKICAgIHRhc2sgPSBydW5fc2Nhbl90YXNrLmRlbGF5KHNjYW4uaWQsIHJlcS5yZXBvX3VybCkKICAgIHNjYW4udGFza19pZCA9IHRhc2suaWQKICAgIGRiLmNvbW1pdCgpCiAgICBkYi5yZWZyZXNoKHNjYW4pCiAgICByZXR1cm4gc2NhbgoKQHJvdXRlci5nZXQoIiIsIHJlc3BvbnNlX21vZGVsPUxpc3RbU2Nhbk91dF0pCmRlZiBsaXN0X3NjYW5zKGRiOiBTZXNzaW9uID0gRGVwZW5kcyhnZXRfZGIpLAogICAgICAgICAgICAgICBjdXJyZW50X3VzZXI6IFVzZXIgPSBEZXBlbmRzKGdldF9jdXJyZW50X3VzZXIpKToKICAgIHJldHVybiBkYi5xdWVyeShTY2FuKS5maWx0ZXIoU2Nhbi51c2VyX2lkID09IGN1cnJlbnRfdXNlci5pZClcCiAgICAgICAgICAgICAub3JkZXJfYnkoU2Nhbi5jcmVhdGVkX2F0LmRlc2MoKSkuYWxsKCkKCkByb3V0ZXIuZ2V0KCIve3NjYW5faWR9IiwgcmVzcG9uc2VfbW9kZWw9U2Nhbk91dCkKZGVmIGdldF9zY2FuKHNjYW5faWQ6IGludCwgZGI6IFNlc3Npb24gPSBEZXBlbmRzKGdldF9kYiksCiAgICAgICAgICAgICBjdXJyZW50X3VzZXI6IFVzZXIgPSBEZXBlbmRzKGdldF9jdXJyZW50X3VzZXIpKToKICAgIHNjYW4gPSBkYi5xdWVyeShTY2FuKS5maWx0ZXIoU2Nhbi5pZCA9PSBzY2FuX2lkLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgU2Nhbi51c2VyX2lkID09IGN1cnJlbnRfdXNlci5pZCkuZmlyc3QoKQogICAgaWYgbm90IHNjYW46CiAgICAgICAgcmFpc2UgSFRUUEV4Y2VwdGlvbihzdGF0dXNfY29kZT00MDQsIGRldGFpbD0iU2NhbiBub3QgZm91bmQiKQogICAgcmV0dXJuIHNjYW4KCkByb3V0ZXIuZGVsZXRlKCIve3NjYW5faWR9Iiwgc3RhdHVzX2NvZGU9MjA0KQpkZWYgZGVsZXRlX3NjYW4oc2Nhbl9pZDogaW50LCBkYjogU2Vzc2lvbiA9IERlcGVuZHMoZ2V0X2RiKSwKICAgICAgICAgICAgICAgIGN1cnJlbnRfdXNlcjogVXNlciA9IERlcGVuZHMoZ2V0X2N1cnJlbnRfdXNlcikpOgogICAgc2NhbiA9IGRiLnF1ZXJ5KFNjYW4pLmZpbHRlcihTY2FuLmlkID09IHNjYW5faWQsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBTY2FuLnVzZXJfaWQgPT0gY3VycmVudF91c2VyLmlkKS5maXJzdCgpCiAgICBpZiBub3Qgc2NhbjoKICAgICAgICByYWlzZSBIVFRQRXhjZXB0aW9uKHN0YXR1c19jb2RlPTQwNCwgZGV0YWlsPSJTY2FuIG5vdCBmb3VuZCIpCiAgICBkYi5kZWxldGUoc2NhbikKICAgIGRiLmNvbW1pdCgpCg=="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/api/routes/scan.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/core/__init__.py
$b64 = ""
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/core/__init__.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/core/config.py
$b64 = "ZnJvbSBweWRhbnRpY19zZXR0aW5ncyBpbXBvcnQgQmFzZVNldHRpbmdzCgpjbGFzcyBTZXR0aW5ncyhCYXNlU2V0dGluZ3MpOgogICAgREFUQUJBU0VfVVJMOiBzdHIKICAgIFNFQ1JFVF9LRVk6IHN0cgogICAgQUxHT1JJVEhNOiBzdHIgPSAiSFMyNTYiCiAgICBBQ0NFU1NfVE9LRU5fRVhQSVJFX01JTlVURVM6IGludCA9IDYwCiAgICBPUEVOQUlfQVBJX0tFWTogc3RyID0gIiIKICAgIEFOVEhST1BJQ19BUElfS0VZOiBzdHIgPSAiIgogICAgR0lUSFVCX1RPS0VOOiBzdHIgPSAiIgogICAgUkVESVNfVVJMOiBzdHIgPSAicmVkaXM6Ly9yZWRpczo2Mzc5LzAiCgogICAgY2xhc3MgQ29uZmlnOgogICAgICAgIGVudl9maWxlID0gIi5lbnYiCgpzZXR0aW5ncyA9IFNldHRpbmdzKCkK"
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/core/config.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/core/database.py
$b64 = "ZnJvbSBzcWxhbGNoZW15IGltcG9ydCBjcmVhdGVfZW5naW5lCmZyb20gc3FsYWxjaGVteS5vcm0gaW1wb3J0IHNlc3Npb25tYWtlciwgRGVjbGFyYXRpdmVCYXNlCmZyb20gYXBwLmNvcmUuY29uZmlnIGltcG9ydCBzZXR0aW5ncwoKZW5naW5lID0gY3JlYXRlX2VuZ2luZShzZXR0aW5ncy5EQVRBQkFTRV9VUkwpClNlc3Npb25Mb2NhbCA9IHNlc3Npb25tYWtlcihhdXRvY29tbWl0PUZhbHNlLCBhdXRvZmx1c2g9RmFsc2UsIGJpbmQ9ZW5naW5lKQoKY2xhc3MgQmFzZShEZWNsYXJhdGl2ZUJhc2UpOgogICAgcGFzcwoKZGVmIGdldF9kYigpOgogICAgZGIgPSBTZXNzaW9uTG9jYWwoKQogICAgdHJ5OgogICAgICAgIHlpZWxkIGRiCiAgICBmaW5hbGx5OgogICAgICAgIGRiLmNsb3NlKCkK"
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/core/database.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/core/security.py
$b64 = "ZnJvbSBqb3NlIGltcG9ydCBqd3QsIEpXVEVycm9yCmZyb20gZGF0ZXRpbWUgaW1wb3J0IGRhdGV0aW1lLCB0aW1lZGVsdGEKZnJvbSBwYXNzbGliLmNvbnRleHQgaW1wb3J0IENyeXB0Q29udGV4dApmcm9tIGZhc3RhcGkgaW1wb3J0IERlcGVuZHMsIEhUVFBFeGNlcHRpb24sIHN0YXR1cwpmcm9tIGZhc3RhcGkuc2VjdXJpdHkgaW1wb3J0IE9BdXRoMlBhc3N3b3JkQmVhcmVyCmZyb20gc3FsYWxjaGVteS5vcm0gaW1wb3J0IFNlc3Npb24KZnJvbSBhcHAuY29yZS5jb25maWcgaW1wb3J0IHNldHRpbmdzCmZyb20gYXBwLmNvcmUuZGF0YWJhc2UgaW1wb3J0IGdldF9kYgoKcHdkX2NvbnRleHQgPSBDcnlwdENvbnRleHQoc2NoZW1lcz1bImJjcnlwdCJdLCBkZXByZWNhdGVkPSJhdXRvIikKb2F1dGgyX3NjaGVtZSA9IE9BdXRoMlBhc3N3b3JkQmVhcmVyKHRva2VuVXJsPSIvYXV0aC9sb2dpbiIpCgpkZWYgaGFzaF9wYXNzd29yZChwYXNzd29yZDogc3RyKSAtPiBzdHI6CiAgICByZXR1cm4gcHdkX2NvbnRleHQuaGFzaChwYXNzd29yZCkKCmRlZiB2ZXJpZnlfcGFzc3dvcmQocGxhaW46IHN0ciwgaGFzaGVkOiBzdHIpIC0+IGJvb2w6CiAgICByZXR1cm4gcHdkX2NvbnRleHQudmVyaWZ5KHBsYWluLCBoYXNoZWQpCgpkZWYgY3JlYXRlX2FjY2Vzc190b2tlbihkYXRhOiBkaWN0KSAtPiBzdHI6CiAgICBwYXlsb2FkID0gZGF0YS5jb3B5KCkKICAgIHBheWxvYWRbImV4cCJdID0gZGF0ZXRpbWUudXRjbm93KCkgKyB0aW1lZGVsdGEobWludXRlcz1zZXR0aW5ncy5BQ0NFU1NfVE9LRU5fRVhQSVJFX01JTlVURVMpCiAgICByZXR1cm4gand0LmVuY29kZShwYXlsb2FkLCBzZXR0aW5ncy5TRUNSRVRfS0VZLCBhbGdvcml0aG09c2V0dGluZ3MuQUxHT1JJVEhNKQoKZGVmIGRlY29kZV90b2tlbih0b2tlbjogc3RyKSAtPiBkaWN0OgogICAgdHJ5OgogICAgICAgIHJldHVybiBqd3QuZGVjb2RlKHRva2VuLCBzZXR0aW5ncy5TRUNSRVRfS0VZLCBhbGdvcml0aG1zPVtzZXR0aW5ncy5BTEdPUklUSE1dKQogICAgZXhjZXB0IEpXVEVycm9yOgogICAgICAgIHJhaXNlIEhUVFBFeGNlcHRpb24oc3RhdHVzX2NvZGU9c3RhdHVzLkhUVFBfNDAxX1VOQVVUSE9SSVpFRCwgZGV0YWlsPSJJbnZhbGlkIHRva2VuIikKCmRlZiBnZXRfY3VycmVudF91c2VyKHRva2VuOiBzdHIgPSBEZXBlbmRzKG9hdXRoMl9zY2hlbWUpLCBkYjogU2Vzc2lvbiA9IERlcGVuZHMoZ2V0X2RiKSk6CiAgICBmcm9tIGFwcC5tb2RlbHMudXNlciBpbXBvcnQgVXNlcgogICAgcGF5bG9hZCA9IGRlY29kZV90b2tlbih0b2tlbikKICAgIHVzZXJfaWQgPSBwYXlsb2FkLmdldCgic3ViIikKICAgIGlmIHVzZXJfaWQgaXMgTm9uZToKICAgICAgICByYWlzZSBIVFRQRXhjZXB0aW9uKHN0YXR1c19jb2RlPTQwMSwgZGV0YWlsPSJJbnZhbGlkIHRva2VuIHBheWxvYWQiKQogICAgdXNlciA9IGRiLnF1ZXJ5KFVzZXIpLmZpbHRlcihVc2VyLmlkID09IGludCh1c2VyX2lkKSkuZmlyc3QoKQogICAgaWYgbm90IHVzZXI6CiAgICAgICAgcmFpc2UgSFRUUEV4Y2VwdGlvbihzdGF0dXNfY29kZT00MDEsIGRldGFpbD0iVXNlciBub3QgZm91bmQiKQogICAgcmV0dXJuIHVzZXIK"
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/core/security.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/main.py
$b64 = "ZnJvbSBmYXN0YXBpIGltcG9ydCBGYXN0QVBJCmZyb20gZmFzdGFwaS5taWRkbGV3YXJlLmNvcnMgaW1wb3J0IENPUlNNaWRkbGV3YXJlCmZyb20gYXBwLmFwaS5yb3V0ZXMgaW1wb3J0IGF1dGgsIHNjYW4sIHJlcG9ydHMKZnJvbSBhcHAuY29yZS5kYXRhYmFzZSBpbXBvcnQgZW5naW5lLCBCYXNlCgpCYXNlLm1ldGFkYXRhLmNyZWF0ZV9hbGwoYmluZD1lbmdpbmUpCgphcHAgPSBGYXN0QVBJKAogICAgdGl0bGU9IkFJIFN0YXRpYyBWdWxuZXJhYmlsaXR5IFNjYW5uZXIiLAogICAgZGVzY3JpcHRpb249IlNBU1QgcGxhdGZvcm0gcG93ZXJlZCBieSBBU1QgYW5hbHlzaXMgKyBMTE0gZXhwbGFuYXRpb25zIiwKICAgIHZlcnNpb249IjEuMC4wIiwKKQoKYXBwLmFkZF9taWRkbGV3YXJlKAogICAgQ09SU01pZGRsZXdhcmUsCiAgICBhbGxvd19vcmlnaW5zPVsiKiJdLAogICAgYWxsb3dfbWV0aG9kcz1bIioiXSwKICAgIGFsbG93X2hlYWRlcnM9WyIqIl0sCikKCmFwcC5pbmNsdWRlX3JvdXRlcihhdXRoLnJvdXRlcikKYXBwLmluY2x1ZGVfcm91dGVyKHNjYW4ucm91dGVyKQphcHAuaW5jbHVkZV9yb3V0ZXIocmVwb3J0cy5yb3V0ZXIpCgpAYXBwLmdldCgiLyIsIHRhZ3M9WyJoZWFsdGgiXSkKZGVmIHJvb3QoKToKICAgIHJldHVybiB7InN0YXR1cyI6ICJvayIsICJtZXNzYWdlIjogIkFJIFN0YXRpYyBWdWxuZXJhYmlsaXR5IFNjYW5uZXIifQoKQGFwcC5nZXQoIi9oZWFsdGgiLCB0YWdzPVsiaGVhbHRoIl0pCmRlZiBoZWFsdGgoKToKICAgIHJldHVybiB7InN0YXR1cyI6ICJoZWFsdGh5In0K"
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/main.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/models/__init__.py
$b64 = ""
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/models/__init__.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/models/scan.py
$b64 = "ZnJvbSBzcWxhbGNoZW15IGltcG9ydCBDb2x1bW4sIEludGVnZXIsIFN0cmluZywgRGF0ZVRpbWUsIEZvcmVpZ25LZXkKZnJvbSBzcWxhbGNoZW15Lm9ybSBpbXBvcnQgcmVsYXRpb25zaGlwCmZyb20gZGF0ZXRpbWUgaW1wb3J0IGRhdGV0aW1lCmZyb20gYXBwLmNvcmUuZGF0YWJhc2UgaW1wb3J0IEJhc2UKCmNsYXNzIFNjYW4oQmFzZSk6CiAgICBfX3RhYmxlbmFtZV9fID0gInNjYW5zIgogICAgaWQgPSBDb2x1bW4oSW50ZWdlciwgcHJpbWFyeV9rZXk9VHJ1ZSwgaW5kZXg9VHJ1ZSkKICAgIHJlcG9fdXJsID0gQ29sdW1uKFN0cmluZywgbnVsbGFibGU9RmFsc2UpCiAgICBzdGF0dXMgPSBDb2x1bW4oU3RyaW5nLCBkZWZhdWx0PSJxdWV1ZWQiKQogICAgdGFza19pZCA9IENvbHVtbihTdHJpbmcsIG51bGxhYmxlPVRydWUpCiAgICB1c2VyX2lkID0gQ29sdW1uKEludGVnZXIsIEZvcmVpZ25LZXkoInVzZXJzLmlkIiksIG51bGxhYmxlPVRydWUpCiAgICBjcmVhdGVkX2F0ID0gQ29sdW1uKERhdGVUaW1lLCBkZWZhdWx0PWRhdGV0aW1lLnV0Y25vdykKICAgIGNvbXBsZXRlZF9hdCA9IENvbHVtbihEYXRlVGltZSwgbnVsbGFibGU9VHJ1ZSkKICAgIHZ1bG5lcmFiaWxpdGllcyA9IHJlbGF0aW9uc2hpcCgiVnVsbmVyYWJpbGl0eSIsIGJhY2tfcG9wdWxhdGVzPSJzY2FuIiwgY2FzY2FkZT0iYWxsLCBkZWxldGUiKQo="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/models/scan.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/models/user.py
$b64 = "ZnJvbSBzcWxhbGNoZW15IGltcG9ydCBDb2x1bW4sIEludGVnZXIsIFN0cmluZwpmcm9tIGFwcC5jb3JlLmRhdGFiYXNlIGltcG9ydCBCYXNlCgpjbGFzcyBVc2VyKEJhc2UpOgogICAgX190YWJsZW5hbWVfXyA9ICJ1c2VycyIKICAgIGlkID0gQ29sdW1uKEludGVnZXIsIHByaW1hcnlfa2V5PVRydWUsIGluZGV4PVRydWUpCiAgICBlbWFpbCA9IENvbHVtbihTdHJpbmcsIHVuaXF1ZT1UcnVlLCBpbmRleD1UcnVlLCBudWxsYWJsZT1GYWxzZSkKICAgIGhhc2hlZF9wYXNzd29yZCA9IENvbHVtbihTdHJpbmcsIG51bGxhYmxlPUZhbHNlKQo="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/models/user.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/models/vulnerability.py
$b64 = "ZnJvbSBzcWxhbGNoZW15IGltcG9ydCBDb2x1bW4sIEludGVnZXIsIFN0cmluZywgVGV4dCwgRm9yZWlnbktleQpmcm9tIHNxbGFsY2hlbXkub3JtIGltcG9ydCByZWxhdGlvbnNoaXAKZnJvbSBhcHAuY29yZS5kYXRhYmFzZSBpbXBvcnQgQmFzZQoKT1dBU1BfTUFQID0gewogICAgIlNRTCBJbmplY3Rpb24iOiAgICAgICAgICAgICJBMDM6MjAyMSAtIEluamVjdGlvbiIsCiAgICAiQ29tbWFuZCBJbmplY3Rpb24iOiAgICAgICAgIkEwMzoyMDIxIC0gSW5qZWN0aW9uIiwKICAgICJYU1MiOiAgICAgICAgICAgICAgICAgICAgICAiQTAzOjIwMjEgLSBJbmplY3Rpb24iLAogICAgIkhhcmRjb2RlZCBTZWNyZXQiOiAgICAgICAgICJBMDI6MjAyMSAtIENyeXB0b2dyYXBoaWMgRmFpbHVyZXMiLAogICAgIkluc2VjdXJlIERlc2VyaWFsaXphdGlvbiI6ICJBMDg6MjAyMSAtIFNvZnR3YXJlIGFuZCBEYXRhIEludGVncml0eSBGYWlsdXJlcyIsCiAgICAiUGF0aCBUcmF2ZXJzYWwiOiAgICAgICAgICAgIkEwMToyMDIxIC0gQnJva2VuIEFjY2VzcyBDb250cm9sIiwKfQoKY2xhc3MgVnVsbmVyYWJpbGl0eShCYXNlKToKICAgIF9fdGFibGVuYW1lX18gPSAidnVsbmVyYWJpbGl0aWVzIgogICAgaWQgPSBDb2x1bW4oSW50ZWdlciwgcHJpbWFyeV9rZXk9VHJ1ZSwgaW5kZXg9VHJ1ZSkKICAgIHNjYW5faWQgPSBDb2x1bW4oSW50ZWdlciwgRm9yZWlnbktleSgic2NhbnMuaWQiKSwgbnVsbGFibGU9RmFsc2UpCiAgICBmaWxlID0gQ29sdW1uKFN0cmluZykKICAgIGxpbmUgPSBDb2x1bW4oSW50ZWdlcikKICAgIHNldmVyaXR5ID0gQ29sdW1uKFN0cmluZykKICAgIGNhdGVnb3J5ID0gQ29sdW1uKFN0cmluZykKICAgIGRlc2NyaXB0aW9uID0gQ29sdW1uKFRleHQpCiAgICBvd2FzcCA9IENvbHVtbihTdHJpbmcpCiAgICBhaV9leHBsYW5hdGlvbiA9IENvbHVtbihUZXh0LCBudWxsYWJsZT1UcnVlKQogICAgc2NhbiA9IHJlbGF0aW9uc2hpcCgiU2NhbiIsIGJhY2tfcG9wdWxhdGVzPSJ2dWxuZXJhYmlsaXRpZXMiKQo="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/models/vulnerability.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/scanners/__init__.py
$b64 = ""
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/scanners/__init__.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/scanners/ast_engine.py
$b64 = "aW1wb3J0IGFzdApmcm9tIGFwcC5zY2FubmVycy5ydWxlcy5zcWxfaW5qZWN0aW9uIGltcG9ydCBkZXRlY3Rfc3FsX2luamVjdGlvbgpmcm9tIGFwcC5zY2FubmVycy5ydWxlcy5jb21tYW5kX2luamVjdGlvbiBpbXBvcnQgZGV0ZWN0X2NvbW1hbmRfaW5qZWN0aW9uCmZyb20gYXBwLnNjYW5uZXJzLnJ1bGVzLmhhcmRjb2RlZF9zZWNyZXRzIGltcG9ydCBkZXRlY3RfaGFyZGNvZGVkX3NlY3JldHMKZnJvbSBhcHAuc2Nhbm5lcnMucnVsZXMueHNzIGltcG9ydCBkZXRlY3RfeHNzCmZyb20gYXBwLnNjYW5uZXJzLnJ1bGVzLmluc2VjdXJlX2Rlc2VyaWFsaXphdGlvbiBpbXBvcnQgZGV0ZWN0X2luc2VjdXJlX2Rlc2VyaWFsaXphdGlvbgpmcm9tIGFwcC5tb2RlbHMudnVsbmVyYWJpbGl0eSBpbXBvcnQgT1dBU1BfTUFQCgpjbGFzcyBWdWxuZXJhYmlsaXR5U2Nhbm5lcihhc3QuTm9kZVZpc2l0b3IpOgogICAgZGVmIF9faW5pdF9fKHNlbGYpOgogICAgICAgIHNlbGYuZmluZGluZ3MgPSBbXQoKICAgIGRlZiB2aXNpdF9DYWxsKHNlbGYsIG5vZGUpOgogICAgICAgIHNlbGYuZmluZGluZ3MuZXh0ZW5kKGRldGVjdF9zcWxfaW5qZWN0aW9uKG5vZGUpKQogICAgICAgIHNlbGYuZmluZGluZ3MuZXh0ZW5kKGRldGVjdF9jb21tYW5kX2luamVjdGlvbihub2RlKSkKICAgICAgICBzZWxmLmZpbmRpbmdzLmV4dGVuZChkZXRlY3RfeHNzKG5vZGUpKQogICAgICAgIHNlbGYuZmluZGluZ3MuZXh0ZW5kKGRldGVjdF9pbnNlY3VyZV9kZXNlcmlhbGl6YXRpb24obm9kZSkpCiAgICAgICAgc2VsZi5nZW5lcmljX3Zpc2l0KG5vZGUpCgogICAgZGVmIHZpc2l0X0Fzc2lnbihzZWxmLCBub2RlKToKICAgICAgICBzZWxmLmZpbmRpbmdzLmV4dGVuZChkZXRlY3RfaGFyZGNvZGVkX3NlY3JldHMobm9kZSkpCiAgICAgICAgc2VsZi5nZW5lcmljX3Zpc2l0KG5vZGUpCgpkZWYgc2Nhbl9weXRob25fZmlsZShwYXRoOiBzdHIpIC0+IGxpc3Q6CiAgICB0cnk6CiAgICAgICAgd2l0aCBvcGVuKHBhdGgsICJyIiwgZW5jb2Rpbmc9InV0Zi04IiwgZXJyb3JzPSJpZ25vcmUiKSBhcyBmOgogICAgICAgICAgICBzb3VyY2UgPSBmLnJlYWQoKQogICAgICAgIHRyZWUgPSBhc3QucGFyc2Uoc291cmNlLCBmaWxlbmFtZT1wYXRoKQogICAgICAgIHNjYW5uZXIgPSBWdWxuZXJhYmlsaXR5U2Nhbm5lcigpCiAgICAgICAgc2Nhbm5lci52aXNpdCh0cmVlKQogICAgICAgIGZvciBmaW5kaW5nIGluIHNjYW5uZXIuZmluZGluZ3M6CiAgICAgICAgICAgIGZpbmRpbmdbIm93YXNwIl0gPSBPV0FTUF9NQVAuZ2V0KGZpbmRpbmdbImNhdGVnb3J5Il0sICJTZWUgT1dBU1AgVG9wIDEwIikKICAgICAgICByZXR1cm4gc2Nhbm5lci5maW5kaW5ncwogICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICByZXR1cm4gW10K"
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/scanners/ast_engine.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/scanners/repo_downloader.py
$b64 = "aW1wb3J0IHRlbXBmaWxlLCBzaHV0aWwKZnJvbSBnaXQgaW1wb3J0IFJlcG8sIEdpdENvbW1hbmRFcnJvcgpmcm9tIGZhc3RhcGkgaW1wb3J0IEhUVFBFeGNlcHRpb24KCmRlZiBjbG9uZV9yZXBvKHJlcG9fdXJsOiBzdHIpIC0+IHN0cjoKICAgIHRtcCA9IHRlbXBmaWxlLm1rZHRlbXAocHJlZml4PSJzY2FubmVyXyIpCiAgICB0cnk6CiAgICAgICAgUmVwby5jbG9uZV9mcm9tKHJlcG9fdXJsLCB0bXAsIGRlcHRoPTEpCiAgICAgICAgcmV0dXJuIHRtcAogICAgZXhjZXB0IEdpdENvbW1hbmRFcnJvciBhcyBlOgogICAgICAgIHNodXRpbC5ybXRyZWUodG1wLCBpZ25vcmVfZXJyb3JzPVRydWUpCiAgICAgICAgcmFpc2UgSFRUUEV4Y2VwdGlvbihzdGF0dXNfY29kZT00MDAsIGRldGFpbD1mIkZhaWxlZCB0byBjbG9uZSByZXBvOiB7ZX0iKQo="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/scanners/repo_downloader.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/scanners/rules/__init__.py
$b64 = ""
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/scanners/rules/__init__.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/scanners/rules/command_injection.py
$b64 = "aW1wb3J0IGFzdAoKREFOR0VST1VTID0gWyJzeXN0ZW0iLCAicG9wZW4iLCAiY2FsbCIsICJydW4iLCAiUG9wZW4iLCAiY2hlY2tfb3V0cHV0IiwgImNoZWNrX2NhbGwiXQoKZGVmIGRldGVjdF9jb21tYW5kX2luamVjdGlvbihub2RlKToKICAgIGZpbmRpbmdzID0gW10KICAgIGZ1bmMgPSBub2RlLmZ1bmMKICAgIGF0dHIgPSBOb25lCiAgICBpZiBpc2luc3RhbmNlKGZ1bmMsIGFzdC5BdHRyaWJ1dGUpOgogICAgICAgIGF0dHIgPSBmdW5jLmF0dHIKICAgIGVsaWYgaXNpbnN0YW5jZShmdW5jLCBhc3QuTmFtZSk6CiAgICAgICAgYXR0ciA9IGZ1bmMuaWQKICAgIGlmIGF0dHIgaW4gREFOR0VST1VTOgogICAgICAgIGlmIG5vZGUuYXJncyBhbmQgbm90IGlzaW5zdGFuY2Uobm9kZS5hcmdzWzBdLCBhc3QuQ29uc3RhbnQpOgogICAgICAgICAgICBmaW5kaW5ncy5hcHBlbmQoewogICAgICAgICAgICAgICAgImNhdGVnb3J5IjogIkNvbW1hbmQgSW5qZWN0aW9uIiwKICAgICAgICAgICAgICAgICJzZXZlcml0eSI6ICJIaWdoIiwKICAgICAgICAgICAgICAgICJsaW5lIjogbm9kZS5saW5lbm8sCiAgICAgICAgICAgICAgICAiZGVzY3JpcHRpb24iOiBmIkNhbGwgdG8gYHthdHRyfWAgd2l0aCBub24tbGl0ZXJhbCBhcmd1bWVudCBtYXkgYWxsb3cgY29tbWFuZCBpbmplY3Rpb24uIiwKICAgICAgICAgICAgfSkKICAgIHJldHVybiBmaW5kaW5ncwo="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/scanners/rules/command_injection.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/scanners/rules/hardcoded_secrets.py
$b64 = "aW1wb3J0IGFzdAoKU0VDUkVUX05BTUVTID0gWyJwYXNzd29yZCIsICJwYXNzd2QiLCAic2VjcmV0IiwgInRva2VuIiwgImFwaWtleSIsICJhcGlfa2V5IiwgInByaXZhdGVfa2V5Il0KCmRlZiBkZXRlY3RfaGFyZGNvZGVkX3NlY3JldHMobm9kZSk6CiAgICBmaW5kaW5ncyA9IFtdCiAgICBmb3IgdGFyZ2V0IGluIG5vZGUudGFyZ2V0czoKICAgICAgICBpZiBpc2luc3RhbmNlKHRhcmdldCwgYXN0Lk5hbWUpOgogICAgICAgICAgICBuYW1lID0gdGFyZ2V0LmlkLmxvd2VyKCkKICAgICAgICAgICAgaWYgYW55KHMgaW4gbmFtZSBmb3IgcyBpbiBTRUNSRVRfTkFNRVMpOgogICAgICAgICAgICAgICAgaWYgaXNpbnN0YW5jZShub2RlLnZhbHVlLCBhc3QuQ29uc3RhbnQpIGFuZCBpc2luc3RhbmNlKG5vZGUudmFsdWUudmFsdWUsIHN0cik6CiAgICAgICAgICAgICAgICAgICAgdmFsID0gbm9kZS52YWx1ZS52YWx1ZS5zdHJpcCgpCiAgICAgICAgICAgICAgICAgICAgaWYgdmFsIGFuZCB2YWwgbm90IGluICgiIiwgInlvdXJfa2V5X2hlcmUiLCAieHh4IiwgImNoYW5nZW1lIiwgIiIpOgogICAgICAgICAgICAgICAgICAgICAgICBmaW5kaW5ncy5hcHBlbmQoewogICAgICAgICAgICAgICAgICAgICAgICAgICAgImNhdGVnb3J5IjogIkhhcmRjb2RlZCBTZWNyZXQiLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgInNldmVyaXR5IjogIkNyaXRpY2FsIiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICJsaW5lIjogbm9kZS5saW5lbm8sCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAiZGVzY3JpcHRpb24iOiBmIkhhcmRjb2RlZCBjcmVkZW50aWFsIGluIGB7dGFyZ2V0LmlkfWAgLSB1c2UgZW52aXJvbm1lbnQgdmFyaWFibGVzLiIsCiAgICAgICAgICAgICAgICAgICAgICAgIH0pCiAgICByZXR1cm4gZmluZGluZ3MK"
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/scanners/rules/hardcoded_secrets.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/scanners/rules/insecure_deserialization.py
$b64 = "aW1wb3J0IGFzdAoKVU5TQUZFID0geyJwaWNrbGUiOiBbImxvYWRzIiwgImxvYWQiXSwgInlhbWwiOiBbImxvYWQiXSwgIm1hcnNoYWwiOiBbImxvYWRzIl19CgpkZWYgZGV0ZWN0X2luc2VjdXJlX2Rlc2VyaWFsaXphdGlvbihub2RlKToKICAgIGZpbmRpbmdzID0gW10KICAgIGZ1bmMgPSBub2RlLmZ1bmMKICAgIGlmIGlzaW5zdGFuY2UoZnVuYywgYXN0LkF0dHJpYnV0ZSk6CiAgICAgICAgbW9kdWxlID0gZnVuYy52YWx1ZS5pZCBpZiBpc2luc3RhbmNlKGZ1bmMudmFsdWUsIGFzdC5OYW1lKSBlbHNlICIiCiAgICAgICAgaWYgbW9kdWxlIGluIFVOU0FGRSBhbmQgZnVuYy5hdHRyIGluIFVOU0FGRVttb2R1bGVdOgogICAgICAgICAgICBmaW5kaW5ncy5hcHBlbmQoewogICAgICAgICAgICAgICAgImNhdGVnb3J5IjogIkluc2VjdXJlIERlc2VyaWFsaXphdGlvbiIsCiAgICAgICAgICAgICAgICAic2V2ZXJpdHkiOiAiSGlnaCIsCiAgICAgICAgICAgICAgICAibGluZSI6IG5vZGUubGluZW5vLAogICAgICAgICAgICAgICAgImRlc2NyaXB0aW9uIjogZiJge21vZHVsZX0ue2Z1bmMuYXR0cn1gIGlzIHVuc2FmZSAtIHVzZSBzYWZlIGFsdGVybmF0aXZlcy4iLAogICAgICAgICAgICB9KQogICAgcmV0dXJuIGZpbmRpbmdzCg=="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/scanners/rules/insecure_deserialization.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/scanners/rules/sql_injection.py
$b64 = "aW1wb3J0IGFzdAoKZGVmIGRldGVjdF9zcWxfaW5qZWN0aW9uKG5vZGUpOgogICAgZmluZGluZ3MgPSBbXQogICAgaWYgaXNpbnN0YW5jZShub2RlLmZ1bmMsIGFzdC5BdHRyaWJ1dGUpIGFuZCBub2RlLmZ1bmMuYXR0ciBpbiAoImV4ZWN1dGUiLCAiZXhlY3V0ZW1hbnkiKToKICAgICAgICBmb3IgYXJnIGluIG5vZGUuYXJnczoKICAgICAgICAgICAgaWYgaXNpbnN0YW5jZShhcmcsIChhc3QuQmluT3AsIGFzdC5Kb2luZWRTdHIpKToKICAgICAgICAgICAgICAgIGZpbmRpbmdzLmFwcGVuZCh7CiAgICAgICAgICAgICAgICAgICAgImNhdGVnb3J5IjogIlNRTCBJbmplY3Rpb24iLAogICAgICAgICAgICAgICAgICAgICJzZXZlcml0eSI6ICJDcml0aWNhbCIsCiAgICAgICAgICAgICAgICAgICAgImxpbmUiOiBub2RlLmxpbmVubywKICAgICAgICAgICAgICAgICAgICAiZGVzY3JpcHRpb24iOiAiU1FMIHF1ZXJ5IGJ1aWx0IHZpYSBzdHJpbmcgY29uY2F0ZW5hdGlvbiAtIHVzZSBwYXJhbWV0ZXJpemVkIHF1ZXJpZXMuIiwKICAgICAgICAgICAgICAgIH0pCiAgICByZXR1cm4gZmluZGluZ3MK"
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/scanners/rules/sql_injection.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/scanners/rules/xss.py
$b64 = "aW1wb3J0IGFzdAoKWFNTX1NJTktTID0gWyJyZW5kZXIiLCAicmVuZGVyX3RlbXBsYXRlX3N0cmluZyIsICJNYXJrdXAiLCAiaW5uZXJIVE1MIl0KCmRlZiBkZXRlY3RfeHNzKG5vZGUpOgogICAgZmluZGluZ3MgPSBbXQogICAgZnVuYyA9IG5vZGUuZnVuYwogICAgbmFtZSA9IE5vbmUKICAgIGlmIGlzaW5zdGFuY2UoZnVuYywgYXN0LkF0dHJpYnV0ZSk6CiAgICAgICAgbmFtZSA9IGZ1bmMuYXR0cgogICAgZWxpZiBpc2luc3RhbmNlKGZ1bmMsIGFzdC5OYW1lKToKICAgICAgICBuYW1lID0gZnVuYy5pZAogICAgaWYgbmFtZSBpbiBYU1NfU0lOS1M6CiAgICAgICAgZm9yIGFyZyBpbiBub2RlLmFyZ3M6CiAgICAgICAgICAgIGlmIG5vdCBpc2luc3RhbmNlKGFyZywgYXN0LkNvbnN0YW50KToKICAgICAgICAgICAgICAgIGZpbmRpbmdzLmFwcGVuZCh7CiAgICAgICAgICAgICAgICAgICAgImNhdGVnb3J5IjogIlhTUyIsCiAgICAgICAgICAgICAgICAgICAgInNldmVyaXR5IjogIkhpZ2giLAogICAgICAgICAgICAgICAgICAgICJsaW5lIjogbm9kZS5saW5lbm8sCiAgICAgICAgICAgICAgICAgICAgImRlc2NyaXB0aW9uIjogZiJge25hbWV9YCBjYWxsZWQgd2l0aCB1c2VyLWNvbnRyb2xsZWQgaW5wdXQgLSBtYXkgYWxsb3cgcmVmbGVjdGVkIFhTUy4iLAogICAgICAgICAgICAgICAgfSkKICAgIHJldHVybiBmaW5kaW5ncwo="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/scanners/rules/xss.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/schemas/__init__.py
$b64 = ""
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/schemas/__init__.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/schemas/auth.py
$b64 = "ZnJvbSBweWRhbnRpYyBpbXBvcnQgQmFzZU1vZGVsLCBFbWFpbFN0cgoKY2xhc3MgUmVnaXN0ZXJSZXF1ZXN0KEJhc2VNb2RlbCk6CiAgICBlbWFpbDogRW1haWxTdHIKICAgIHBhc3N3b3JkOiBzdHIKCmNsYXNzIExvZ2luUmVzcG9uc2UoQmFzZU1vZGVsKToKICAgIGFjY2Vzc190b2tlbjogc3RyCiAgICB0b2tlbl90eXBlOiBzdHIgPSAiYmVhcmVyIgo="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/schemas/auth.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/schemas/scan.py
$b64 = "ZnJvbSBweWRhbnRpYyBpbXBvcnQgQmFzZU1vZGVsCmZyb20gZGF0ZXRpbWUgaW1wb3J0IGRhdGV0aW1lCmZyb20gdHlwaW5nIGltcG9ydCBPcHRpb25hbCwgTGlzdApmcm9tIGFwcC5zY2hlbWFzLnZ1bG5lcmFiaWxpdHkgaW1wb3J0IFZ1bG5lcmFiaWxpdHlPdXQKCmNsYXNzIFNjYW5SZXF1ZXN0KEJhc2VNb2RlbCk6CiAgICByZXBvX3VybDogc3RyCgpjbGFzcyBTY2FuT3V0KEJhc2VNb2RlbCk6CiAgICBpZDogaW50CiAgICByZXBvX3VybDogc3RyCiAgICBzdGF0dXM6IHN0cgogICAgdGFza19pZDogT3B0aW9uYWxbc3RyXSA9IE5vbmUKICAgIGNyZWF0ZWRfYXQ6IGRhdGV0aW1lCiAgICBjb21wbGV0ZWRfYXQ6IE9wdGlvbmFsW2RhdGV0aW1lXSA9IE5vbmUKICAgIHZ1bG5lcmFiaWxpdGllczogTGlzdFtWdWxuZXJhYmlsaXR5T3V0XSA9IFtdCgogICAgY2xhc3MgQ29uZmlnOgogICAgICAgIGZyb21fYXR0cmlidXRlcyA9IFRydWUK"
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/schemas/scan.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/schemas/vulnerability.py
$b64 = "ZnJvbSBweWRhbnRpYyBpbXBvcnQgQmFzZU1vZGVsCmZyb20gdHlwaW5nIGltcG9ydCBPcHRpb25hbAoKY2xhc3MgVnVsbmVyYWJpbGl0eU91dChCYXNlTW9kZWwpOgogICAgaWQ6IGludAogICAgZmlsZTogT3B0aW9uYWxbc3RyXSA9IE5vbmUKICAgIGxpbmU6IE9wdGlvbmFsW2ludF0gPSBOb25lCiAgICBzZXZlcml0eTogc3RyCiAgICBjYXRlZ29yeTogc3RyCiAgICBkZXNjcmlwdGlvbjogc3RyCiAgICBvd2FzcDogT3B0aW9uYWxbc3RyXSA9IE5vbmUKICAgIGFpX2V4cGxhbmF0aW9uOiBPcHRpb25hbFtzdHJdID0gTm9uZQoKICAgIGNsYXNzIENvbmZpZzoKICAgICAgICBmcm9tX2F0dHJpYnV0ZXMgPSBUcnVlCg=="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/schemas/vulnerability.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/services/__init__.py
$b64 = ""
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/services/__init__.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/services/auth_service.py
$b64 = "ZnJvbSBzcWxhbGNoZW15Lm9ybSBpbXBvcnQgU2Vzc2lvbgpmcm9tIGZhc3RhcGkgaW1wb3J0IEhUVFBFeGNlcHRpb24KZnJvbSBhcHAubW9kZWxzLnVzZXIgaW1wb3J0IFVzZXIKZnJvbSBhcHAuY29yZS5zZWN1cml0eSBpbXBvcnQgaGFzaF9wYXNzd29yZCwgdmVyaWZ5X3Bhc3N3b3JkLCBjcmVhdGVfYWNjZXNzX3Rva2VuCgpkZWYgcmVnaXN0ZXJfdXNlcihlbWFpbDogc3RyLCBwYXNzd29yZDogc3RyLCBkYjogU2Vzc2lvbik6CiAgICBpZiBkYi5xdWVyeShVc2VyKS5maWx0ZXIoVXNlci5lbWFpbCA9PSBlbWFpbCkuZmlyc3QoKToKICAgICAgICByYWlzZSBIVFRQRXhjZXB0aW9uKHN0YXR1c19jb2RlPTQwMCwgZGV0YWlsPSJFbWFpbCBhbHJlYWR5IHJlZ2lzdGVyZWQiKQogICAgdXNlciA9IFVzZXIoZW1haWw9ZW1haWwsIGhhc2hlZF9wYXNzd29yZD1oYXNoX3Bhc3N3b3JkKHBhc3N3b3JkKSkKICAgIGRiLmFkZCh1c2VyKQogICAgZGIuY29tbWl0KCkKICAgIGRiLnJlZnJlc2godXNlcikKICAgIHJldHVybiB1c2VyCgpkZWYgbG9naW5fdXNlcihlbWFpbDogc3RyLCBwYXNzd29yZDogc3RyLCBkYjogU2Vzc2lvbik6CiAgICB1c2VyID0gZGIucXVlcnkoVXNlcikuZmlsdGVyKFVzZXIuZW1haWwgPT0gZW1haWwpLmZpcnN0KCkKICAgIGlmIG5vdCB1c2VyIG9yIG5vdCB2ZXJpZnlfcGFzc3dvcmQocGFzc3dvcmQsIHVzZXIuaGFzaGVkX3Bhc3N3b3JkKToKICAgICAgICByYWlzZSBIVFRQRXhjZXB0aW9uKHN0YXR1c19jb2RlPTQwMSwgZGV0YWlsPSJJbnZhbGlkIGNyZWRlbnRpYWxzIikKICAgIHJldHVybiB7ImFjY2Vzc190b2tlbiI6IGNyZWF0ZV9hY2Nlc3NfdG9rZW4oeyJzdWIiOiBzdHIodXNlci5pZCl9KSwgInRva2VuX3R5cGUiOiAiYmVhcmVyIn0K"
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/services/auth_service.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/services/scan_service.py
$b64 = "aW1wb3J0IG9zLCBzaHV0aWwKZnJvbSBhcHAuc2Nhbm5lcnMuYXN0X2VuZ2luZSBpbXBvcnQgc2Nhbl9weXRob25fZmlsZQpmcm9tIGFwcC5haS5sbG1fY2xpZW50IGltcG9ydCBnZW5lcmF0ZV9haV9leHBsYW5hdGlvbgoKZGVmIHNjYW5fcmVwb3NpdG9yeShyZXBvX3BhdGg6IHN0cikgLT4gbGlzdDoKICAgIGFsbF9maW5kaW5ncyA9IFtdCiAgICBmb3Igcm9vdCwgZGlycywgZmlsZW5hbWVzIGluIG9zLndhbGsocmVwb19wYXRoKToKICAgICAgICBkaXJzWzpdID0gW2QgZm9yIGQgaW4gZGlycyBpZiBub3QgZC5zdGFydHN3aXRoKCIuIildCiAgICAgICAgZm9yIGZpbGVuYW1lIGluIGZpbGVuYW1lczoKICAgICAgICAgICAgaWYgZmlsZW5hbWUuZW5kc3dpdGgoIi5weSIpOgogICAgICAgICAgICAgICAgZmlsZXBhdGggPSBvcy5wYXRoLmpvaW4ocm9vdCwgZmlsZW5hbWUpCiAgICAgICAgICAgICAgICByZWxhdGl2ZSA9IG9zLnBhdGgucmVscGF0aChmaWxlcGF0aCwgcmVwb19wYXRoKQogICAgICAgICAgICAgICAgZmluZGluZ3MgPSBzY2FuX3B5dGhvbl9maWxlKGZpbGVwYXRoKQogICAgICAgICAgICAgICAgZm9yIGYgaW4gZmluZGluZ3M6CiAgICAgICAgICAgICAgICAgICAgZlsiZmlsZSJdID0gcmVsYXRpdmUKICAgICAgICAgICAgICAgICAgICBmWyJhaV9leHBsYW5hdGlvbiJdID0gZ2VuZXJhdGVfYWlfZXhwbGFuYXRpb24oZikKICAgICAgICAgICAgICAgIGFsbF9maW5kaW5ncy5leHRlbmQoZmluZGluZ3MpCiAgICBzaHV0aWwucm10cmVlKHJlcG9fcGF0aCwgaWdub3JlX2Vycm9ycz1UcnVlKQogICAgcmV0dXJuIGFsbF9maW5kaW5ncwo="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/services/scan_service.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/workers/__init__.py
$b64 = ""
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/workers/__init__.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/workers/celery_app.py
$b64 = "ZnJvbSBjZWxlcnkgaW1wb3J0IENlbGVyeQpmcm9tIGFwcC5jb3JlLmNvbmZpZyBpbXBvcnQgc2V0dGluZ3MKCmNlbGVyeV9hcHAgPSBDZWxlcnkoCiAgICAic2Nhbm5lciIsCiAgICBicm9rZXI9c2V0dGluZ3MuUkVESVNfVVJMLAogICAgYmFja2VuZD1zZXR0aW5ncy5SRURJU19VUkwsCiAgICBpbmNsdWRlPVsiYXBwLndvcmtlcnMuc2Nhbl90YXNrcyJdLAopCmNlbGVyeV9hcHAuY29uZi50YXNrX3NlcmlhbGl6ZXIgICA9ICJqc29uIgpjZWxlcnlfYXBwLmNvbmYucmVzdWx0X3NlcmlhbGl6ZXIgPSAianNvbiIKY2VsZXJ5X2FwcC5jb25mLmFjY2VwdF9jb250ZW50ICAgID0gWyJqc29uIl0K"
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/workers/celery_app.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/app/workers/scan_tasks.py
$b64 = "ZnJvbSBhcHAud29ya2Vycy5jZWxlcnlfYXBwIGltcG9ydCBjZWxlcnlfYXBwCmZyb20gYXBwLnNjYW5uZXJzLnJlcG9fZG93bmxvYWRlciBpbXBvcnQgY2xvbmVfcmVwbwpmcm9tIGFwcC5zZXJ2aWNlcy5zY2FuX3NlcnZpY2UgaW1wb3J0IHNjYW5fcmVwb3NpdG9yeQpmcm9tIGFwcC5jb3JlLmRhdGFiYXNlIGltcG9ydCBTZXNzaW9uTG9jYWwKZnJvbSBhcHAubW9kZWxzLnNjYW4gaW1wb3J0IFNjYW4KZnJvbSBhcHAubW9kZWxzLnZ1bG5lcmFiaWxpdHkgaW1wb3J0IFZ1bG5lcmFiaWxpdHkKZnJvbSBkYXRldGltZSBpbXBvcnQgZGF0ZXRpbWUKCkBjZWxlcnlfYXBwLnRhc2soYmluZD1UcnVlLCBtYXhfcmV0cmllcz0zKQpkZWYgcnVuX3NjYW5fdGFzayhzZWxmLCBzY2FuX2lkOiBpbnQsIHJlcG9fdXJsOiBzdHIpOgogICAgZGIgPSBTZXNzaW9uTG9jYWwoKQogICAgdHJ5OgogICAgICAgIHNjYW4gPSBkYi5xdWVyeShTY2FuKS5maWx0ZXIoU2Nhbi5pZCA9PSBzY2FuX2lkKS5maXJzdCgpCiAgICAgICAgaWYgbm90IHNjYW46CiAgICAgICAgICAgIHJldHVybgogICAgICAgIHNjYW4uc3RhdHVzID0gInJ1bm5pbmciCiAgICAgICAgZGIuY29tbWl0KCkKICAgICAgICByZXBvX3BhdGggPSBjbG9uZV9yZXBvKHJlcG9fdXJsKQogICAgICAgIGZpbmRpbmdzICA9IHNjYW5fcmVwb3NpdG9yeShyZXBvX3BhdGgpCiAgICAgICAgZm9yIGYgaW4gZmluZGluZ3M6CiAgICAgICAgICAgIGRiLmFkZChWdWxuZXJhYmlsaXR5KAogICAgICAgICAgICAgICAgc2Nhbl9pZD1zY2FuX2lkLAogICAgICAgICAgICAgICAgZmlsZT1mLmdldCgiZmlsZSIpLAogICAgICAgICAgICAgICAgbGluZT1mLmdldCgibGluZSIpLAogICAgICAgICAgICAgICAgc2V2ZXJpdHk9Zi5nZXQoInNldmVyaXR5IiwgIlVua25vd24iKSwKICAgICAgICAgICAgICAgIGNhdGVnb3J5PWYuZ2V0KCJjYXRlZ29yeSIsICJVbmtub3duIiksCiAgICAgICAgICAgICAgICBkZXNjcmlwdGlvbj1mLmdldCgiZGVzY3JpcHRpb24iLCAiIiksCiAgICAgICAgICAgICAgICBvd2FzcD1mLmdldCgib3dhc3AiLCAiIiksCiAgICAgICAgICAgICAgICBhaV9leHBsYW5hdGlvbj1mLmdldCgiYWlfZXhwbGFuYXRpb24iLCAiIiksCiAgICAgICAgICAgICkpCiAgICAgICAgc2Nhbi5zdGF0dXMgPSAiY29tcGxldGVkIgogICAgICAgIHNjYW4uY29tcGxldGVkX2F0ID0gZGF0ZXRpbWUudXRjbm93KCkKICAgICAgICBkYi5jb21taXQoKQogICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBleGM6CiAgICAgICAgZGIucm9sbGJhY2soKQogICAgICAgIHNjYW4gPSBkYi5xdWVyeShTY2FuKS5maWx0ZXIoU2Nhbi5pZCA9PSBzY2FuX2lkKS5maXJzdCgpCiAgICAgICAgaWYgc2NhbjoKICAgICAgICAgICAgc2Nhbi5zdGF0dXMgPSAiZmFpbGVkIgogICAgICAgICAgICBkYi5jb21taXQoKQogICAgICAgIHJhaXNlIHNlbGYucmV0cnkoZXhjPWV4YywgY291bnRkb3duPTUpCiAgICBmaW5hbGx5OgogICAgICAgIGRiLmNsb3NlKCkK"
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/app/workers/scan_tasks.py")),
    [System.Convert]::FromBase64String($b64)
)

# ---- backend/requirements.txt
$b64 = "ZmFzdGFwaT09MC4xMTEuMAp1dmljb3JuW3N0YW5kYXJkXT09MC4yOS4wCnNxbGFsY2hlbXk9PTIuMC4zMApwc3ljb3BnMi1iaW5hcnk9PTIuOS45CnB5dGhvbi1kb3RlbnY9PTEuMC4xCnB5dGhvbi1qb3NlW2NyeXB0b2dyYXBoeV09PTMuMy4wCnBhc3NsaWJbYmNyeXB0XT09MS43LjQKcHlkYW50aWMtc2V0dGluZ3M9PTIuMi4xCnB5ZGFudGljPT0yLjcuMQpjZWxlcnk9PTUuNC4wCnJlZGlzPT01LjAuNApodHRweD09MC4yNy4wCmdpdHB5dGhvbj09My4xLjQzCm9wZW5haT09MS4zMC4xCmFudGhyb3BpYz09MC4yOC4wCnB5dGhvbi1tdWx0aXBhcnQ9PTAuMC45CnJlcG9ydGxhYj09NC4yLjAKZW1haWwtdmFsaWRhdG9yPT0yLjEuMQo="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/backend/requirements.txt")),
    [System.Convert]::FromBase64String($b64)
)

# ---- docker-compose.yml
$b64 = "dmVyc2lvbjogIjMuOSIKCnNlcnZpY2VzOgogIGRiOgogICAgaW1hZ2U6IHBvc3RncmVzOjE1LWFscGluZQogICAgcmVzdGFydDogdW5sZXNzLXN0b3BwZWQKICAgIGVudmlyb25tZW50OgogICAgICBQT1NUR1JFU19VU0VSOiBwb3N0Z3JlcwogICAgICBQT1NUR1JFU19QQVNTV09SRDogcG9zdGdyZXMKICAgICAgUE9TVEdSRVNfREI6IHNjYW5uZXIKICAgIHZvbHVtZXM6CiAgICAgIC0gcGdkYXRhOi92YXIvbGliL3Bvc3RncmVzcWwvZGF0YQogICAgcG9ydHM6CiAgICAgIC0gIjU0MzI6NTQzMiIKICAgIGhlYWx0aGNoZWNrOgogICAgICB0ZXN0OiBbIkNNRC1TSEVMTCIsICJwZ19pc3JlYWR5IC1VIHBvc3RncmVzIl0KICAgICAgaW50ZXJ2YWw6IDVzCiAgICAgIHRpbWVvdXQ6IDVzCiAgICAgIHJldHJpZXM6IDEwCgogIHJlZGlzOgogICAgaW1hZ2U6IHJlZGlzOjctYWxwaW5lCiAgICByZXN0YXJ0OiB1bmxlc3Mtc3RvcHBlZAogICAgcG9ydHM6CiAgICAgIC0gIjYzNzk6NjM3OSIKICAgIGhlYWx0aGNoZWNrOgogICAgICB0ZXN0OiBbIkNNRCIsICJyZWRpcy1jbGkiLCAicGluZyJdCiAgICAgIGludGVydmFsOiA1cwogICAgICB0aW1lb3V0OiAzcwogICAgICByZXRyaWVzOiAxMAoKICBiYWNrZW5kOgogICAgYnVpbGQ6IC4vYmFja2VuZAogICAgcmVzdGFydDogdW5sZXNzLXN0b3BwZWQKICAgIHBvcnRzOgogICAgICAtICI4MDAwOjgwMDAiCiAgICBlbnZfZmlsZToKICAgICAgLSAuL2JhY2tlbmQvLmVudgogICAgZGVwZW5kc19vbjoKICAgICAgZGI6CiAgICAgICAgY29uZGl0aW9uOiBzZXJ2aWNlX2hlYWx0aHkKICAgICAgcmVkaXM6CiAgICAgICAgY29uZGl0aW9uOiBzZXJ2aWNlX2hlYWx0aHkKICAgIHZvbHVtZXM6CiAgICAgIC0gLi9iYWNrZW5kOi9hcHAKICAgIGNvbW1hbmQ6IHV2aWNvcm4gYXBwLm1haW46YXBwIC0taG9zdCAwLjAuMC4wIC0tcG9ydCA4MDAwIC0tcmVsb2FkCgogIHdvcmtlcjoKICAgIGJ1aWxkOiAuL2JhY2tlbmQKICAgIHJlc3RhcnQ6IHVubGVzcy1zdG9wcGVkCiAgICBlbnZfZmlsZToKICAgICAgLSAuL2JhY2tlbmQvLmVudgogICAgZGVwZW5kc19vbjoKICAgICAgZGI6CiAgICAgICAgY29uZGl0aW9uOiBzZXJ2aWNlX2hlYWx0aHkKICAgICAgcmVkaXM6CiAgICAgICAgY29uZGl0aW9uOiBzZXJ2aWNlX2hlYWx0aHkKICAgIHZvbHVtZXM6CiAgICAgIC0gLi9iYWNrZW5kOi9hcHAKICAgIGNvbW1hbmQ6IGNlbGVyeSAtQSBhcHAud29ya2Vycy5jZWxlcnlfYXBwIHdvcmtlciAtLWxvZ2xldmVsPWluZm8gLS1jb25jdXJyZW5jeT0yCgogIGZyb250ZW5kOgogICAgYnVpbGQ6IC4vZnJvbnRlbmQKICAgIHJlc3RhcnQ6IHVubGVzcy1zdG9wcGVkCiAgICBwb3J0czoKICAgICAgLSAiMzAwMDo4MCIKICAgIGRlcGVuZHNfb246CiAgICAgIC0gYmFja2VuZAoKdm9sdW1lczoKICBwZ2RhdGE6Cg=="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/docker-compose.yml")),
    [System.Convert]::FromBase64String($b64)
)

# ---- frontend/Dockerfile
$b64 = "RlJPTSBub2RlOjIwLWFscGluZSBBUyBidWlsZApXT1JLRElSIC9hcHAKQ09QWSBwYWNrYWdlLmpzb24gLgpSVU4gbnBtIGluc3RhbGwKQ09QWSAuIC4KUlVOIG5wbSBydW4gYnVpbGQKCkZST00gbmdpbng6YWxwaW5lCkNPUFkgLS1mcm9tPWJ1aWxkIC9hcHAvZGlzdCAvdXNyL3NoYXJlL25naW54L2h0bWwKQ09QWSBuZ2lueC5jb25mIC9ldGMvbmdpbngvY29uZi5kL2RlZmF1bHQuY29uZgpFWFBPU0UgODAK"
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/frontend/Dockerfile")),
    [System.Convert]::FromBase64String($b64)
)

# ---- frontend/index.html
$b64 = "PCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9ImVuIj4KICA8aGVhZD4KICAgIDxtZXRhIGNoYXJzZXQ9IlVURi04IiAvPgogICAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjAiIC8+CiAgICA8dGl0bGU+QUkgVnVsbmVyYWJpbGl0eSBTY2FubmVyPC90aXRsZT4KICA8L2hlYWQ+CiAgPGJvZHk+CiAgICA8ZGl2IGlkPSJyb290Ij48L2Rpdj4KICAgIDxzY3JpcHQgdHlwZT0ibW9kdWxlIiBzcmM9Ii9zcmMvbWFpbi5qc3giPjwvc2NyaXB0PgogIDwvYm9keT4KPC9odG1sPgo="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/frontend/index.html")),
    [System.Convert]::FromBase64String($b64)
)

# ---- frontend/nginx.conf
$b64 = "c2VydmVyIHsKICAgIGxpc3RlbiA4MDsKICAgIHJvb3QgL3Vzci9zaGFyZS9uZ2lueC9odG1sOwogICAgaW5kZXggaW5kZXguaHRtbDsKCiAgICBsb2NhdGlvbiAvYXBpLyB7CiAgICAgICAgcHJveHlfcGFzcyBodHRwOi8vYmFja2VuZDo4MDAwLzsKICAgICAgICBwcm94eV9zZXRfaGVhZGVyIEhvc3QgJGhvc3Q7CiAgICAgICAgcHJveHlfc2V0X2hlYWRlciBYLVJlYWwtSVAgJHJlbW90ZV9hZGRyOwogICAgfQoKICAgIGxvY2F0aW9uIC8gewogICAgICAgIHRyeV9maWxlcyAkdXJpICR1cmkvIC9pbmRleC5odG1sOwogICAgfQp9Cg=="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/frontend/nginx.conf")),
    [System.Convert]::FromBase64String($b64)
)

# ---- frontend/package.json
$b64 = "ewogICJuYW1lIjogImFpLXN0YXRpYy1zY2FubmVyLWZyb250ZW5kIiwKICAicHJpdmF0ZSI6IHRydWUsCiAgInZlcnNpb24iOiAiMS4wLjAiLAogICJ0eXBlIjogIm1vZHVsZSIsCiAgInNjcmlwdHMiOiB7CiAgICAiZGV2IjogInZpdGUiLAogICAgImJ1aWxkIjogInZpdGUgYnVpbGQiLAogICAgInByZXZpZXciOiAidml0ZSBwcmV2aWV3IgogIH0sCiAgImRlcGVuZGVuY2llcyI6IHsKICAgICJheGlvcyI6ICJeMS43LjIiLAogICAgInJlYWN0IjogIl4xOC4zLjEiLAogICAgInJlYWN0LWRvbSI6ICJeMTguMy4xIiwKICAgICJyZWFjdC1yb3V0ZXItZG9tIjogIl42LjIzLjEiCiAgfSwKICAiZGV2RGVwZW5kZW5jaWVzIjogewogICAgIkB2aXRlanMvcGx1Z2luLXJlYWN0IjogIl40LjMuMCIsCiAgICAiYXV0b3ByZWZpeGVyIjogIl4xMC40LjE5IiwKICAgICJwb3N0Y3NzIjogIl44LjQuMzgiLAogICAgInRhaWx3aW5kY3NzIjogIl4zLjQuMyIsCiAgICAidml0ZSI6ICJeNS4yLjEyIgogIH0KfQo="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/frontend/package.json")),
    [System.Convert]::FromBase64String($b64)
)

# ---- frontend/postcss.config.js
$b64 = "ZXhwb3J0IGRlZmF1bHQgewogIHBsdWdpbnM6IHsgdGFpbHdpbmRjc3M6IHt9LCBhdXRvcHJlZml4ZXI6IHt9IH0sCn07Cg=="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/frontend/postcss.config.js")),
    [System.Convert]::FromBase64String($b64)
)

# ---- frontend/src/App.jsx
$b64 = "aW1wb3J0IHsgUm91dGVzLCBSb3V0ZSwgTmF2aWdhdGUgfSBmcm9tICJyZWFjdC1yb3V0ZXItZG9tIjsKaW1wb3J0IHsgQXV0aFByb3ZpZGVyLCB1c2VBdXRoIH0gZnJvbSAiLi9jb250ZXh0L0F1dGhDb250ZXh0IjsKaW1wb3J0IExvZ2luUGFnZSAgICAgZnJvbSAiLi9wYWdlcy9Mb2dpblBhZ2UiOwppbXBvcnQgUmVnaXN0ZXJQYWdlICBmcm9tICIuL3BhZ2VzL1JlZ2lzdGVyUGFnZSI7CmltcG9ydCBEYXNoYm9hcmRQYWdlIGZyb20gIi4vcGFnZXMvRGFzaGJvYXJkUGFnZSI7CmltcG9ydCBTY2FuUGFnZSAgICAgIGZyb20gIi4vcGFnZXMvU2NhblBhZ2UiOwppbXBvcnQgUmVzdWx0c1BhZ2UgICBmcm9tICIuL3BhZ2VzL1Jlc3VsdHNQYWdlIjsKaW1wb3J0IE5hdmJhciAgICAgICAgZnJvbSAiLi9jb21wb25lbnRzL05hdmJhciI7CgpmdW5jdGlvbiBQcml2YXRlUm91dGUoeyBjaGlsZHJlbiB9KSB7CiAgY29uc3QgeyBpc0F1dGggfSA9IHVzZUF1dGgoKTsKICByZXR1cm4gaXNBdXRoID8gY2hpbGRyZW4gOiA8TmF2aWdhdGUgdG89Ii9sb2dpbiIgLz47Cn0KCmV4cG9ydCBkZWZhdWx0IGZ1bmN0aW9uIEFwcCgpIHsKICByZXR1cm4gKAogICAgPEF1dGhQcm92aWRlcj4KICAgICAgPE5hdmJhciAvPgogICAgICA8Um91dGVzPgogICAgICAgIDxSb3V0ZSBwYXRoPSIvbG9naW4iICAgICAgIGVsZW1lbnQ9ezxMb2dpblBhZ2UgLz59IC8+CiAgICAgICAgPFJvdXRlIHBhdGg9Ii9yZWdpc3RlciIgICAgZWxlbWVudD17PFJlZ2lzdGVyUGFnZSAvPn0gLz4KICAgICAgICA8Um91dGUgcGF0aD0iLyIgICAgICAgICAgICBlbGVtZW50PXs8UHJpdmF0ZVJvdXRlPjxEYXNoYm9hcmRQYWdlIC8+PC9Qcml2YXRlUm91dGU+fSAvPgogICAgICAgIDxSb3V0ZSBwYXRoPSIvc2NhbiIgICAgICAgIGVsZW1lbnQ9ezxQcml2YXRlUm91dGU+PFNjYW5QYWdlIC8+PC9Qcml2YXRlUm91dGU+fSAvPgogICAgICAgIDxSb3V0ZSBwYXRoPSIvcmVzdWx0cy86aWQiIGVsZW1lbnQ9ezxQcml2YXRlUm91dGU+PFJlc3VsdHNQYWdlIC8+PC9Qcml2YXRlUm91dGU+fSAvPgogICAgICA8L1JvdXRlcz4KICAgIDwvQXV0aFByb3ZpZGVyPgogICk7Cn0K"
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/frontend/src/App.jsx")),
    [System.Convert]::FromBase64String($b64)
)

# ---- frontend/src/components/Navbar.jsx
$b64 = "aW1wb3J0IHsgTGluayB9IGZyb20gInJlYWN0LXJvdXRlci1kb20iOwppbXBvcnQgeyB1c2VBdXRoIH0gZnJvbSAiLi4vY29udGV4dC9BdXRoQ29udGV4dCI7CgpleHBvcnQgZGVmYXVsdCBmdW5jdGlvbiBOYXZiYXIoKSB7CiAgY29uc3QgeyBpc0F1dGgsIGxvZ291dCB9ID0gdXNlQXV0aCgpOwogIHJldHVybiAoCiAgICA8bmF2IGNsYXNzTmFtZT0iYmctc2xhdGUtOTAwIGJvcmRlci1iIGJvcmRlci1zbGF0ZS03MDAgcHgtNiBweS0zIGZsZXggaXRlbXMtY2VudGVyIGp1c3RpZnktYmV0d2VlbiI+CiAgICAgIDxMaW5rIHRvPSIvIiBjbGFzc05hbWU9InRleHQtY3lhbi00MDAgZm9udC1ib2xkIHRleHQtbGciPnNoaWVsZCBBSSBTY2FubmVyPC9MaW5rPgogICAgICA8ZGl2IGNsYXNzTmFtZT0iZmxleCBnYXAtNCB0ZXh0LXNtIj4KICAgICAgICB7aXNBdXRoID8gKAogICAgICAgICAgPD4KICAgICAgICAgICAgPExpbmsgdG89Ii8iICAgICBjbGFzc05hbWU9InRleHQtc2xhdGUtMzAwIGhvdmVyOnRleHQtd2hpdGUiPkRhc2hib2FyZDwvTGluaz4KICAgICAgICAgICAgPExpbmsgdG89Ii9zY2FuIiBjbGFzc05hbWU9InRleHQtc2xhdGUtMzAwIGhvdmVyOnRleHQtd2hpdGUiPk5ldyBTY2FuPC9MaW5rPgogICAgICAgICAgICA8YnV0dG9uIG9uQ2xpY2s9e2xvZ291dH0gY2xhc3NOYW1lPSJ0ZXh0LXJlZC00MDAgaG92ZXI6dGV4dC1yZWQtMzAwIj5Mb2dvdXQ8L2J1dHRvbj4KICAgICAgICAgIDwvPgogICAgICAgICkgOiAoCiAgICAgICAgICA8PgogICAgICAgICAgICA8TGluayB0bz0iL2xvZ2luIiAgICBjbGFzc05hbWU9InRleHQtc2xhdGUtMzAwIGhvdmVyOnRleHQtd2hpdGUiPkxvZ2luPC9MaW5rPgogICAgICAgICAgICA8TGluayB0bz0iL3JlZ2lzdGVyIiBjbGFzc05hbWU9InRleHQtc2xhdGUtMzAwIGhvdmVyOnRleHQtd2hpdGUiPlJlZ2lzdGVyPC9MaW5rPgogICAgICAgICAgPC8+CiAgICAgICAgKX0KICAgICAgPC9kaXY+CiAgICA8L25hdj4KICApOwp9Cg=="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/frontend/src/components/Navbar.jsx")),
    [System.Convert]::FromBase64String($b64)
)

# ---- frontend/src/components/VulnCard.jsx
$b64 = "aW1wb3J0IHsgdXNlU3RhdGUgfSBmcm9tICJyZWFjdCI7Cgpjb25zdCBTRVZfQk9SREVSID0geyBDcml0aWNhbDoiYm9yZGVyLXJlZC01MDAgYmctcmVkLTkwMC8yMCIsIEhpZ2g6ImJvcmRlci1vcmFuZ2UtNDAwIGJnLW9yYW5nZS05MDAvMjAiLCBNZWRpdW06ImJvcmRlci15ZWxsb3ctNDAwIGJnLXllbGxvdy05MDAvMjAiLCBMb3c6ImJvcmRlci1ncmVlbi00MDAgYmctZ3JlZW4tOTAwLzIwIiB9Owpjb25zdCBTRVZfQkFER0UgID0geyBDcml0aWNhbDoiYmctcmVkLTYwMCIsIEhpZ2g6ImJnLW9yYW5nZS01MDAiLCBNZWRpdW06ImJnLXllbGxvdy01MDAgdGV4dC1ibGFjayIsIExvdzoiYmctZ3JlZW4tNjAwIiB9OwoKZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gVnVsbkNhcmQoeyB2dWxuIH0pIHsKICBjb25zdCBbb3Blbiwgc2V0T3Blbl0gPSB1c2VTdGF0ZShmYWxzZSk7CiAgcmV0dXJuICgKICAgIDxkaXYgY2xhc3NOYW1lPXsiYm9yZGVyIHJvdW5kZWQtbGcgcC00IG1iLTMgIiArIChTRVZfQk9SREVSW3Z1bG4uc2V2ZXJpdHldIHx8ICJib3JkZXItc2xhdGUtNjAwIil9PgogICAgICA8ZGl2IGNsYXNzTmFtZT0iZmxleCBpdGVtcy1jZW50ZXIganVzdGlmeS1iZXR3ZWVuIGN1cnNvci1wb2ludGVyIiBvbkNsaWNrPXsoKSA9PiBzZXRPcGVuKCFvcGVuKX0+CiAgICAgICAgPGRpdj4KICAgICAgICAgIDxzcGFuIGNsYXNzTmFtZT17InRleHQteHMgZm9udC1ib2xkIHB4LTIgcHktMC41IHJvdW5kZWQgbXItMiAiICsgKFNFVl9CQURHRVt2dWxuLnNldmVyaXR5XSB8fCAiYmctc2xhdGUtNjAwIil9Pnt2dWxuLnNldmVyaXR5fTwvc3Bhbj4KICAgICAgICAgIDxzcGFuIGNsYXNzTmFtZT0iZm9udC1zZW1pYm9sZCB0ZXh0LXdoaXRlIj57dnVsbi5jYXRlZ29yeX08L3NwYW4+CiAgICAgICAgICA8c3BhbiBjbGFzc05hbWU9InRleHQtc2xhdGUtNDAwIHRleHQtc20gbWwtMyI+e3Z1bG4uZmlsZX06e3Z1bG4ubGluZX08L3NwYW4+CiAgICAgICAgPC9kaXY+CiAgICAgICAgPHNwYW4gY2xhc3NOYW1lPSJ0ZXh0LXNsYXRlLTQwMCI+e29wZW4gPyAi4payIiA6ICLilrwifTwvc3Bhbj4KICAgICAgPC9kaXY+CiAgICAgIHtvcGVuICYmICgKICAgICAgICA8ZGl2IGNsYXNzTmFtZT0ibXQtMyBzcGFjZS15LTIiPgogICAgICAgICAgPHAgY2xhc3NOYW1lPSJ0ZXh0LXNsYXRlLTMwMCB0ZXh0LXNtIj48c3Ryb25nPk9XQVNQOjwvc3Ryb25nPiB7dnVsbi5vd2FzcH08L3A+CiAgICAgICAgICA8cCBjbGFzc05hbWU9InRleHQtc2xhdGUtMzAwIHRleHQtc20iPjxzdHJvbmc+SXNzdWU6PC9zdHJvbmc+IHt2dWxuLmRlc2NyaXB0aW9ufTwvcD4KICAgICAgICAgIHt2dWxuLmFpX2V4cGxhbmF0aW9uICYmICgKICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9ImJnLXNsYXRlLTgwMCByb3VuZGVkIHAtMyBtdC0yIj4KICAgICAgICAgICAgICA8cCBjbGFzc05hbWU9InRleHQtY3lhbi00MDAgdGV4dC14cyBmb250LWJvbGQgbWItMSI+QUkgRXhwbGFuYXRpb248L3A+CiAgICAgICAgICAgICAgPHByZSBjbGFzc05hbWU9InRleHQtc2xhdGUtMjAwIHRleHQteHMgd2hpdGVzcGFjZS1wcmUtd3JhcCI+e3Z1bG4uYWlfZXhwbGFuYXRpb259PC9wcmU+CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgKX0KICAgICAgICA8L2Rpdj4KICAgICAgKX0KICAgIDwvZGl2PgogICk7Cn0K"
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/frontend/src/components/VulnCard.jsx")),
    [System.Convert]::FromBase64String($b64)
)

# ---- frontend/src/context/AuthContext.jsx
$b64 = "aW1wb3J0IHsgY3JlYXRlQ29udGV4dCwgdXNlQ29udGV4dCwgdXNlU3RhdGUgfSBmcm9tICJyZWFjdCI7Cgpjb25zdCBBdXRoQ29udGV4dCA9IGNyZWF0ZUNvbnRleHQobnVsbCk7CgpleHBvcnQgZnVuY3Rpb24gQXV0aFByb3ZpZGVyKHsgY2hpbGRyZW4gfSkgewogIGNvbnN0IFt0b2tlbiwgc2V0VG9rZW5dID0gdXNlU3RhdGUobG9jYWxTdG9yYWdlLmdldEl0ZW0oInRva2VuIikpOwogIGNvbnN0IGxvZ2luICA9ICh0KSA9PiB7IHNldFRva2VuKHQpOyBsb2NhbFN0b3JhZ2Uuc2V0SXRlbSgidG9rZW4iLCB0KTsgfTsKICBjb25zdCBsb2dvdXQgPSAoKSAgPT4geyBzZXRUb2tlbihudWxsKTsgbG9jYWxTdG9yYWdlLnJlbW92ZUl0ZW0oInRva2VuIik7IH07CiAgcmV0dXJuICgKICAgIDxBdXRoQ29udGV4dC5Qcm92aWRlciB2YWx1ZT17eyB0b2tlbiwgbG9naW4sIGxvZ291dCwgaXNBdXRoOiAhIXRva2VuIH19PgogICAgICB7Y2hpbGRyZW59CiAgICA8L0F1dGhDb250ZXh0LlByb3ZpZGVyPgogICk7Cn0KCmV4cG9ydCBjb25zdCB1c2VBdXRoID0gKCkgPT4gdXNlQ29udGV4dChBdXRoQ29udGV4dCk7Cg=="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/frontend/src/context/AuthContext.jsx")),
    [System.Convert]::FromBase64String($b64)
)

# ---- frontend/src/index.css
$b64 = "QHRhaWx3aW5kIGJhc2U7CkB0YWlsd2luZCBjb21wb25lbnRzOwpAdGFpbHdpbmQgdXRpbGl0aWVzOwpib2R5IHsgYmFja2dyb3VuZDogIzBmMTcyYTsgY29sb3I6ICNlMmU4ZjA7IH0K"
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/frontend/src/index.css")),
    [System.Convert]::FromBase64String($b64)
)

# ---- frontend/src/main.jsx
$b64 = "aW1wb3J0IFJlYWN0IGZyb20gInJlYWN0IjsKaW1wb3J0IFJlYWN0RE9NIGZyb20gInJlYWN0LWRvbS9jbGllbnQiOwppbXBvcnQgeyBCcm93c2VyUm91dGVyIH0gZnJvbSAicmVhY3Qtcm91dGVyLWRvbSI7CmltcG9ydCBBcHAgZnJvbSAiLi9BcHAiOwppbXBvcnQgIi4vaW5kZXguY3NzIjsKClJlYWN0RE9NLmNyZWF0ZVJvb3QoZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoInJvb3QiKSkucmVuZGVyKAogIDxSZWFjdC5TdHJpY3RNb2RlPgogICAgPEJyb3dzZXJSb3V0ZXI+CiAgICAgIDxBcHAgLz4KICAgIDwvQnJvd3NlclJvdXRlcj4KICA8L1JlYWN0LlN0cmljdE1vZGU+Cik7Cg=="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/frontend/src/main.jsx")),
    [System.Convert]::FromBase64String($b64)
)

# ---- frontend/src/pages/DashboardPage.jsx
$b64 = "aW1wb3J0IHsgdXNlRWZmZWN0LCB1c2VTdGF0ZSB9IGZyb20gInJlYWN0IjsKaW1wb3J0IHsgTGluayB9IGZyb20gInJlYWN0LXJvdXRlci1kb20iOwppbXBvcnQgYXBpIGZyb20gIi4uL3NlcnZpY2VzL2FwaSI7Cgpjb25zdCBTVEFUVVNfQkFER0UgPSB7CiAgY29tcGxldGVkOiAiYmctZ3JlZW4tNzAwIHRleHQtZ3JlZW4tMTAwIiwKICBydW5uaW5nOiAgICJiZy1ibHVlLTcwMCB0ZXh0LWJsdWUtMTAwIiwKICBxdWV1ZWQ6ICAgICJiZy15ZWxsb3ctNzAwIHRleHQteWVsbG93LTEwMCIsCiAgZmFpbGVkOiAgICAiYmctcmVkLTcwMCB0ZXh0LXJlZC0xMDAiLAp9OwoKZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gRGFzaGJvYXJkUGFnZSgpIHsKICBjb25zdCBbc2NhbnMsICAgc2V0U2NhbnNdICAgPSB1c2VTdGF0ZShbXSk7CiAgY29uc3QgW2xvYWRpbmcsIHNldExvYWRpbmddID0gdXNlU3RhdGUodHJ1ZSk7CgogIHVzZUVmZmVjdCgoKSA9PiB7CiAgICBjb25zdCBmZXRjaCA9IGFzeW5jICgpID0+IHsKICAgICAgdHJ5IHsgY29uc3QgcmVzID0gYXdhaXQgYXBpLmdldCgiL3NjYW4iKTsgc2V0U2NhbnMocmVzLmRhdGEpOyB9CiAgICAgIGNhdGNoIHsgc2V0U2NhbnMoW10pOyB9CiAgICAgIGZpbmFsbHkgeyBzZXRMb2FkaW5nKGZhbHNlKTsgfQogICAgfTsKICAgIGZldGNoKCk7CiAgICBjb25zdCBpZCA9IHNldEludGVydmFsKGZldGNoLCA1MDAwKTsKICAgIHJldHVybiAoKSA9PiBjbGVhckludGVydmFsKGlkKTsKICB9LCBbXSk7CgogIHJldHVybiAoCiAgICA8ZGl2IGNsYXNzTmFtZT0ibWF4LXctNHhsIG14LWF1dG8gbXQtMTAgcHgtNCI+CiAgICAgIDxkaXYgY2xhc3NOYW1lPSJmbGV4IGl0ZW1zLWNlbnRlciBqdXN0aWZ5LWJldHdlZW4gbWItOCI+CiAgICAgICAgPGgxIGNsYXNzTmFtZT0idGV4dC0zeGwgZm9udC1ib2xkIHRleHQtd2hpdGUiPkRhc2hib2FyZDwvaDE+CiAgICAgICAgPExpbmsgdG89Ii9zY2FuIiBjbGFzc05hbWU9ImJnLWN5YW4tNjAwIGhvdmVyOmJnLWN5YW4tNTAwIHRleHQtd2hpdGUgcHgtNCBweS0yIHJvdW5kZWQtbGcgdGV4dC1zbSBmb250LWJvbGQgdHJhbnNpdGlvbiI+KyBOZXcgU2NhbjwvTGluaz4KICAgICAgPC9kaXY+CiAgICAgIHtsb2FkaW5nICYmIDxwIGNsYXNzTmFtZT0idGV4dC1zbGF0ZS00MDAiPkxvYWRpbmcuLi48L3A+fQogICAgICB7IWxvYWRpbmcgJiYgc2NhbnMubGVuZ3RoID09PSAwICYmICgKICAgICAgICA8ZGl2IGNsYXNzTmFtZT0idGV4dC1jZW50ZXIgcHktMjAiPgogICAgICAgICAgPHAgY2xhc3NOYW1lPSJ0ZXh0LXNsYXRlLTQwMCB0ZXh0LWxnIG1iLTQiPk5vIHNjYW5zIHlldC48L3A+CiAgICAgICAgICA8TGluayB0bz0iL3NjYW4iIGNsYXNzTmFtZT0idGV4dC1jeWFuLTQwMCBob3Zlcjp1bmRlcmxpbmUiPlN0YXJ0IHlvdXIgZmlyc3Qgc2NhbjwvTGluaz4KICAgICAgICA8L2Rpdj4KICAgICAgKX0KICAgICAge3NjYW5zLm1hcChzID0+ICgKICAgICAgICA8TGluayB0bz17Ii9yZXN1bHRzLyIgKyBzLmlkfSBrZXk9e3MuaWR9CiAgICAgICAgICBjbGFzc05hbWU9ImJsb2NrIGJnLXNsYXRlLTgwMCBob3Zlcjpib3JkZXItY3lhbi01MDAgYm9yZGVyIGJvcmRlci1zbGF0ZS03MDAgcm91bmRlZC14bCBwLTUgbWItNCB0cmFuc2l0aW9uIj4KICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJmbGV4IGl0ZW1zLWNlbnRlciBqdXN0aWZ5LWJldHdlZW4iPgogICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgIDxwIGNsYXNzTmFtZT0idGV4dC13aGl0ZSBmb250LXNlbWlib2xkIHRydW5jYXRlIG1heC13LXNtIj57cy5yZXBvX3VybH08L3A+CiAgICAgICAgICAgICAgPHAgY2xhc3NOYW1lPSJ0ZXh0LXNsYXRlLTUwMCB0ZXh0LXhzIG10LTEiPntuZXcgRGF0ZShzLmNyZWF0ZWRfYXQpLnRvTG9jYWxlU3RyaW5nKCl9PC9wPgogICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9InRleHQtcmlnaHQiPgogICAgICAgICAgICAgIDxzcGFuIGNsYXNzTmFtZT17InRleHQteHMgcHgtMiBweS0xIHJvdW5kZWQgZm9udC1ib2xkICIgKyAoU1RBVFVTX0JBREdFW3Muc3RhdHVzXSB8fCAiYmctc2xhdGUtNjAwIil9PgogICAgICAgICAgICAgICAge3Muc3RhdHVzLnRvVXBwZXJDYXNlKCl9CiAgICAgICAgICAgICAgPC9zcGFuPgogICAgICAgICAgICAgIHtzLnN0YXR1cyA9PT0gImNvbXBsZXRlZCIgJiYgKAogICAgICAgICAgICAgICAgPHAgY2xhc3NOYW1lPSJ0ZXh0LXNsYXRlLTQwMCB0ZXh0LXhzIG10LTEiPntzLnZ1bG5lcmFiaWxpdGllcz8ubGVuZ3RoIHx8IDB9IGZpbmRpbmdzPC9wPgogICAgICAgICAgICAgICl9CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgPC9kaXY+CiAgICAgICAgPC9MaW5rPgogICAgICApKX0KICAgIDwvZGl2PgogICk7Cn0K"
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/frontend/src/pages/DashboardPage.jsx")),
    [System.Convert]::FromBase64String($b64)
)

# ---- frontend/src/pages/LoginPage.jsx
$b64 = "aW1wb3J0IHsgdXNlU3RhdGUgfSBmcm9tICJyZWFjdCI7CmltcG9ydCB7IHVzZU5hdmlnYXRlLCBMaW5rIH0gZnJvbSAicmVhY3Qtcm91dGVyLWRvbSI7CmltcG9ydCB7IHVzZUF1dGggfSBmcm9tICIuLi9jb250ZXh0L0F1dGhDb250ZXh0IjsKaW1wb3J0IGFwaSBmcm9tICIuLi9zZXJ2aWNlcy9hcGkiOwoKZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gTG9naW5QYWdlKCkgewogIGNvbnN0IFtlbWFpbCwgc2V0RW1haWxdID0gdXNlU3RhdGUoIiIpOwogIGNvbnN0IFtwYXNzLCAgc2V0UGFzc10gID0gdXNlU3RhdGUoIiIpOwogIGNvbnN0IFtlcnJvciwgc2V0RXJyb3JdID0gdXNlU3RhdGUoIiIpOwogIGNvbnN0IHsgbG9naW4gfSA9IHVzZUF1dGgoKTsKICBjb25zdCBuYXYgPSB1c2VOYXZpZ2F0ZSgpOwoKICBjb25zdCBzdWJtaXQgPSBhc3luYyAoZSkgPT4gewogICAgZS5wcmV2ZW50RGVmYXVsdCgpOyBzZXRFcnJvcigiIik7CiAgICB0cnkgewogICAgICBjb25zdCBmb3JtID0gbmV3IFVSTFNlYXJjaFBhcmFtcygpOwogICAgICBmb3JtLmFwcGVuZCgidXNlcm5hbWUiLCBlbWFpbCk7CiAgICAgIGZvcm0uYXBwZW5kKCJwYXNzd29yZCIsIHBhc3MpOwogICAgICBjb25zdCByZXMgPSBhd2FpdCBhcGkucG9zdCgiL2F1dGgvbG9naW4iLCBmb3JtLAogICAgICAgIHsgaGVhZGVyczogeyAiQ29udGVudC1UeXBlIjogImFwcGxpY2F0aW9uL3gtd3d3LWZvcm0tdXJsZW5jb2RlZCIgfSB9KTsKICAgICAgbG9naW4ocmVzLmRhdGEuYWNjZXNzX3Rva2VuKTsKICAgICAgbmF2KCIvIik7CiAgICB9IGNhdGNoIChlcnIpIHsKICAgICAgc2V0RXJyb3IoZXJyLnJlc3BvbnNlPy5kYXRhPy5kZXRhaWwgfHwgIkxvZ2luIGZhaWxlZCIpOwogICAgfQogIH07CgogIHJldHVybiAoCiAgICA8ZGl2IGNsYXNzTmFtZT0ibWluLWgtc2NyZWVuIGZsZXggaXRlbXMtY2VudGVyIGp1c3RpZnktY2VudGVyIj4KICAgICAgPGRpdiBjbGFzc05hbWU9ImJnLXNsYXRlLTgwMCByb3VuZGVkLXhsIHAtOCB3LWZ1bGwgbWF4LXctbWQgc2hhZG93LXhsIj4KICAgICAgICA8aDIgY2xhc3NOYW1lPSJ0ZXh0LTJ4bCBmb250LWJvbGQgdGV4dC13aGl0ZSBtYi02Ij5TaWduIEluPC9oMj4KICAgICAgICB7ZXJyb3IgJiYgPHAgY2xhc3NOYW1lPSJ0ZXh0LXJlZC00MDAgdGV4dC1zbSBtYi00Ij57ZXJyb3J9PC9wPn0KICAgICAgICA8Zm9ybSBvblN1Ym1pdD17c3VibWl0fSBjbGFzc05hbWU9InNwYWNlLXktNCI+CiAgICAgICAgICA8aW5wdXQgY2xhc3NOYW1lPSJ3LWZ1bGwgYmctc2xhdGUtNzAwIHJvdW5kZWQgcHgtNCBweS0yIHRleHQtd2hpdGUgb3V0bGluZS1ub25lIGZvY3VzOnJpbmctMiBmb2N1czpyaW5nLWN5YW4tNTAwIgogICAgICAgICAgICB0eXBlPSJlbWFpbCIgcGxhY2Vob2xkZXI9IkVtYWlsIiB2YWx1ZT17ZW1haWx9IG9uQ2hhbmdlPXtlID0+IHNldEVtYWlsKGUudGFyZ2V0LnZhbHVlKX0gcmVxdWlyZWQgLz4KICAgICAgICAgIDxpbnB1dCBjbGFzc05hbWU9InctZnVsbCBiZy1zbGF0ZS03MDAgcm91bmRlZCBweC00IHB5LTIgdGV4dC13aGl0ZSBvdXRsaW5lLW5vbmUgZm9jdXM6cmluZy0yIGZvY3VzOnJpbmctY3lhbi01MDAiCiAgICAgICAgICAgIHR5cGU9InBhc3N3b3JkIiBwbGFjZWhvbGRlcj0iUGFzc3dvcmQiIHZhbHVlPXtwYXNzfSBvbkNoYW5nZT17ZSA9PiBzZXRQYXNzKGUudGFyZ2V0LnZhbHVlKX0gcmVxdWlyZWQgLz4KICAgICAgICAgIDxidXR0b24gY2xhc3NOYW1lPSJ3LWZ1bGwgYmctY3lhbi02MDAgaG92ZXI6YmctY3lhbi01MDAgdGV4dC13aGl0ZSBmb250LWJvbGQgcHktMiByb3VuZGVkIHRyYW5zaXRpb24iPkxvZ2luPC9idXR0b24+CiAgICAgICAgPC9mb3JtPgogICAgICAgIDxwIGNsYXNzTmFtZT0idGV4dC1zbGF0ZS00MDAgdGV4dC1zbSBtdC00IHRleHQtY2VudGVyIj4KICAgICAgICAgIE5vIGFjY291bnQ/IDxMaW5rIHRvPSIvcmVnaXN0ZXIiIGNsYXNzTmFtZT0idGV4dC1jeWFuLTQwMCBob3Zlcjp1bmRlcmxpbmUiPlJlZ2lzdGVyPC9MaW5rPgogICAgICAgIDwvcD4KICAgICAgPC9kaXY+CiAgICA8L2Rpdj4KICApOwp9Cg=="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/frontend/src/pages/LoginPage.jsx")),
    [System.Convert]::FromBase64String($b64)
)

# ---- frontend/src/pages/RegisterPage.jsx
$b64 = "aW1wb3J0IHsgdXNlU3RhdGUgfSBmcm9tICJyZWFjdCI7CmltcG9ydCB7IHVzZU5hdmlnYXRlLCBMaW5rIH0gZnJvbSAicmVhY3Qtcm91dGVyLWRvbSI7CmltcG9ydCBhcGkgZnJvbSAiLi4vc2VydmljZXMvYXBpIjsKCmV4cG9ydCBkZWZhdWx0IGZ1bmN0aW9uIFJlZ2lzdGVyUGFnZSgpIHsKICBjb25zdCBbZW1haWwsIHNldEVtYWlsXSA9IHVzZVN0YXRlKCIiKTsKICBjb25zdCBbcGFzcywgIHNldFBhc3NdICA9IHVzZVN0YXRlKCIiKTsKICBjb25zdCBbbXNnLCAgIHNldE1zZ10gICA9IHVzZVN0YXRlKCIiKTsKICBjb25zdCBuYXYgPSB1c2VOYXZpZ2F0ZSgpOwoKICBjb25zdCBzdWJtaXQgPSBhc3luYyAoZSkgPT4gewogICAgZS5wcmV2ZW50RGVmYXVsdCgpOyBzZXRNc2coIiIpOwogICAgdHJ5IHsKICAgICAgYXdhaXQgYXBpLnBvc3QoIi9hdXRoL3JlZ2lzdGVyIiwgeyBlbWFpbCwgcGFzc3dvcmQ6IHBhc3MgfSk7CiAgICAgIHNldE1zZygiUmVnaXN0ZXJlZCEgUmVkaXJlY3RpbmcuLi4iKTsKICAgICAgc2V0VGltZW91dCgoKSA9PiBuYXYoIi9sb2dpbiIpLCAxNTAwKTsKICAgIH0gY2F0Y2ggKGVycikgewogICAgICBzZXRNc2coZXJyLnJlc3BvbnNlPy5kYXRhPy5kZXRhaWwgfHwgIlJlZ2lzdHJhdGlvbiBmYWlsZWQiKTsKICAgIH0KICB9OwoKICByZXR1cm4gKAogICAgPGRpdiBjbGFzc05hbWU9Im1pbi1oLXNjcmVlbiBmbGV4IGl0ZW1zLWNlbnRlciBqdXN0aWZ5LWNlbnRlciI+CiAgICAgIDxkaXYgY2xhc3NOYW1lPSJiZy1zbGF0ZS04MDAgcm91bmRlZC14bCBwLTggdy1mdWxsIG1heC13LW1kIHNoYWRvdy14bCI+CiAgICAgICAgPGgyIGNsYXNzTmFtZT0idGV4dC0yeGwgZm9udC1ib2xkIHRleHQtd2hpdGUgbWItNiI+Q3JlYXRlIEFjY291bnQ8L2gyPgogICAgICAgIHttc2cgJiYgPHAgY2xhc3NOYW1lPSJ0ZXh0LWN5YW4tNDAwIHRleHQtc20gbWItNCI+e21zZ308L3A+fQogICAgICAgIDxmb3JtIG9uU3VibWl0PXtzdWJtaXR9IGNsYXNzTmFtZT0ic3BhY2UteS00Ij4KICAgICAgICAgIDxpbnB1dCBjbGFzc05hbWU9InctZnVsbCBiZy1zbGF0ZS03MDAgcm91bmRlZCBweC00IHB5LTIgdGV4dC13aGl0ZSBvdXRsaW5lLW5vbmUgZm9jdXM6cmluZy0yIGZvY3VzOnJpbmctY3lhbi01MDAiCiAgICAgICAgICAgIHR5cGU9ImVtYWlsIiBwbGFjZWhvbGRlcj0iRW1haWwiIHZhbHVlPXtlbWFpbH0gb25DaGFuZ2U9e2UgPT4gc2V0RW1haWwoZS50YXJnZXQudmFsdWUpfSByZXF1aXJlZCAvPgogICAgICAgICAgPGlucHV0IGNsYXNzTmFtZT0idy1mdWxsIGJnLXNsYXRlLTcwMCByb3VuZGVkIHB4LTQgcHktMiB0ZXh0LXdoaXRlIG91dGxpbmUtbm9uZSBmb2N1czpyaW5nLTIgZm9jdXM6cmluZy1jeWFuLTUwMCIKICAgICAgICAgICAgdHlwZT0icGFzc3dvcmQiIHBsYWNlaG9sZGVyPSJQYXNzd29yZCIgdmFsdWU9e3Bhc3N9IG9uQ2hhbmdlPXtlID0+IHNldFBhc3MoZS50YXJnZXQudmFsdWUpfSByZXF1aXJlZCAvPgogICAgICAgICAgPGJ1dHRvbiBjbGFzc05hbWU9InctZnVsbCBiZy1jeWFuLTYwMCBob3ZlcjpiZy1jeWFuLTUwMCB0ZXh0LXdoaXRlIGZvbnQtYm9sZCBweS0yIHJvdW5kZWQgdHJhbnNpdGlvbiI+UmVnaXN0ZXI8L2J1dHRvbj4KICAgICAgICA8L2Zvcm0+CiAgICAgICAgPHAgY2xhc3NOYW1lPSJ0ZXh0LXNsYXRlLTQwMCB0ZXh0LXNtIG10LTQgdGV4dC1jZW50ZXIiPgogICAgICAgICAgSGF2ZSBhbiBhY2NvdW50PyA8TGluayB0bz0iL2xvZ2luIiBjbGFzc05hbWU9InRleHQtY3lhbi00MDAgaG92ZXI6dW5kZXJsaW5lIj5Mb2dpbjwvTGluaz4KICAgICAgICA8L3A+CiAgICAgIDwvZGl2PgogICAgPC9kaXY+CiAgKTsKfQo="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/frontend/src/pages/RegisterPage.jsx")),
    [System.Convert]::FromBase64String($b64)
)

# ---- frontend/src/pages/ResultsPage.jsx
$b64 = "aW1wb3J0IHsgdXNlRWZmZWN0LCB1c2VTdGF0ZSwgdXNlUmVmIH0gZnJvbSAicmVhY3QiOwppbXBvcnQgeyB1c2VQYXJhbXMsIExpbmsgfSBmcm9tICJyZWFjdC1yb3V0ZXItZG9tIjsKaW1wb3J0IGFwaSBmcm9tICIuLi9zZXJ2aWNlcy9hcGkiOwppbXBvcnQgVnVsbkNhcmQgZnJvbSAiLi4vY29tcG9uZW50cy9WdWxuQ2FyZCI7Cgpjb25zdCBTVEFUVVNfQ09MT1IgPSB7IGNvbXBsZXRlZDoidGV4dC1ncmVlbi00MDAiLCBydW5uaW5nOiJ0ZXh0LWJsdWUtNDAwIiwgcXVldWVkOiJ0ZXh0LXllbGxvdy00MDAiLCBmYWlsZWQ6InRleHQtcmVkLTQwMCIgfTsKCmV4cG9ydCBkZWZhdWx0IGZ1bmN0aW9uIFJlc3VsdHNQYWdlKCkgewogIGNvbnN0IHsgaWQgfSA9IHVzZVBhcmFtcygpOwogIGNvbnN0IFtzY2FuLCAgICBzZXRTY2FuXSAgICA9IHVzZVN0YXRlKG51bGwpOwogIGNvbnN0IFtsb2FkaW5nLCBzZXRMb2FkaW5nXSA9IHVzZVN0YXRlKHRydWUpOwogIGNvbnN0IHN0YXR1c1JlZiA9IHVzZVJlZihudWxsKTsKCiAgY29uc3QgZmV0Y2hTY2FuID0gYXN5bmMgKCkgPT4gewogICAgdHJ5IHsKICAgICAgY29uc3QgcmVzID0gYXdhaXQgYXBpLmdldCgiL3NjYW4vIiArIGlkKTsKICAgICAgc2V0U2NhbihyZXMuZGF0YSk7CiAgICAgIHN0YXR1c1JlZi5jdXJyZW50ID0gcmVzLmRhdGEuc3RhdHVzOwogICAgfSBjYXRjaCB7IHNldFNjYW4obnVsbCk7IH0KICAgIGZpbmFsbHkgeyBzZXRMb2FkaW5nKGZhbHNlKTsgfQogIH07CgogIHVzZUVmZmVjdCgoKSA9PiB7CiAgICBmZXRjaFNjYW4oKTsKICAgIGNvbnN0IGludGVydmFsID0gc2V0SW50ZXJ2YWwoKCkgPT4gewogICAgICBpZiAoWyJxdWV1ZWQiLCJydW5uaW5nIl0uaW5jbHVkZXMoc3RhdHVzUmVmLmN1cnJlbnQpKSBmZXRjaFNjYW4oKTsKICAgIH0sIDMwMDApOwogICAgcmV0dXJuICgpID0+IGNsZWFySW50ZXJ2YWwoaW50ZXJ2YWwpOwogIH0sIFtpZF0pOwoKICBpZiAobG9hZGluZykgIHJldHVybiA8ZGl2IGNsYXNzTmFtZT0idGV4dC1jZW50ZXIgbXQtMjAgdGV4dC1zbGF0ZS00MDAiPkxvYWRpbmcuLi48L2Rpdj47CiAgaWYgKCFzY2FuKSAgICByZXR1cm4gPGRpdiBjbGFzc05hbWU9InRleHQtY2VudGVyIG10LTIwIHRleHQtcmVkLTQwMCI+U2NhbiBub3QgZm91bmQuPC9kaXY+OwoKICBjb25zdCBjcml0Q291bnQgPSAoc2Nhbi52dWxuZXJhYmlsaXRpZXMgfHwgW10pLmZpbHRlcih2ID0+IHYuc2V2ZXJpdHkgPT09ICJDcml0aWNhbCIpLmxlbmd0aDsKICBjb25zdCBoaWdoQ291bnQgPSAoc2Nhbi52dWxuZXJhYmlsaXRpZXMgfHwgW10pLmZpbHRlcih2ID0+IHYuc2V2ZXJpdHkgPT09ICJIaWdoIikubGVuZ3RoOwoKICByZXR1cm4gKAogICAgPGRpdiBjbGFzc05hbWU9Im1heC13LTR4bCBteC1hdXRvIG10LTEwIHB4LTQgcGItMjAiPgogICAgICA8TGluayB0bz0iLyIgY2xhc3NOYW1lPSJ0ZXh0LXNsYXRlLTQwMCBob3Zlcjp0ZXh0LXdoaXRlIHRleHQtc20iPkJhY2sgdG8gRGFzaGJvYXJkPC9MaW5rPgogICAgICA8ZGl2IGNsYXNzTmFtZT0ibXQtNCBiZy1zbGF0ZS04MDAgcm91bmRlZC14bCBwLTYgbWItNiI+CiAgICAgICAgPGgxIGNsYXNzTmFtZT0idGV4dC0yeGwgZm9udC1ib2xkIHRleHQtd2hpdGUgbWItMSBicmVhay1hbGwiPntzY2FuLnJlcG9fdXJsfTwvaDE+CiAgICAgICAgPHAgY2xhc3NOYW1lPSJ0ZXh0LXNsYXRlLTQwMCB0ZXh0LXNtIj5TY2FuICN7c2Nhbi5pZH0gLSB7bmV3IERhdGUoc2Nhbi5jcmVhdGVkX2F0KS50b0xvY2FsZVN0cmluZygpfTwvcD4KICAgICAgICA8cCBjbGFzc05hbWU9eyJmb250LWJvbGQgbXQtMiAiICsgKFNUQVRVU19DT0xPUltzY2FuLnN0YXR1c10gfHwgInRleHQtd2hpdGUiKX0+CiAgICAgICAgICB7c2Nhbi5zdGF0dXMudG9VcHBlckNhc2UoKX0ge1sicXVldWVkIiwicnVubmluZyJdLmluY2x1ZGVzKHNjYW4uc3RhdHVzKSAmJiAiKHJlZnJlc2hpbmcuLi4pIn0KICAgICAgICA8L3A+CiAgICAgICAge3NjYW4uc3RhdHVzID09PSAiY29tcGxldGVkIiAmJiAoCiAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0iZmxleCBnYXAtNiBtdC00Ij4KICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9InRleHQtY2VudGVyIj48cCBjbGFzc05hbWU9InRleHQtM3hsIGZvbnQtYm9sZCB0ZXh0LXJlZC00MDAiPntjcml0Q291bnR9PC9wPjxwIGNsYXNzTmFtZT0idGV4dC1zbGF0ZS00MDAgdGV4dC14cyI+Q3JpdGljYWw8L3A+PC9kaXY+CiAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJ0ZXh0LWNlbnRlciI+PHAgY2xhc3NOYW1lPSJ0ZXh0LTN4bCBmb250LWJvbGQgdGV4dC1vcmFuZ2UtNDAwIj57aGlnaENvdW50fTwvcD48cCBjbGFzc05hbWU9InRleHQtc2xhdGUtNDAwIHRleHQteHMiPkhpZ2g8L3A+PC9kaXY+CiAgICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJ0ZXh0LWNlbnRlciI+PHAgY2xhc3NOYW1lPSJ0ZXh0LTN4bCBmb250LWJvbGQgdGV4dC13aGl0ZSI+e3NjYW4udnVsbmVyYWJpbGl0aWVzPy5sZW5ndGggfHwgMH08L3A+PHAgY2xhc3NOYW1lPSJ0ZXh0LXNsYXRlLTQwMCB0ZXh0LXhzIj5Ub3RhbDwvcD48L2Rpdj4KICAgICAgICAgIDwvZGl2PgogICAgICAgICl9CiAgICAgICAge3NjYW4uc3RhdHVzID09PSAiY29tcGxldGVkIiAmJiAoCiAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0iZmxleCBnYXAtMyBtdC00Ij4KICAgICAgICAgICAgPGEgaHJlZj17Ii9hcGkvcmVwb3J0cy8iICsgaWQgKyAiL3BkZiJ9IHRhcmdldD0iX2JsYW5rIgogICAgICAgICAgICAgIGNsYXNzTmFtZT0iYmctc2xhdGUtNzAwIGhvdmVyOmJnLXNsYXRlLTYwMCB0ZXh0LXdoaXRlIHRleHQtc20gcHgtNCBweS0yIHJvdW5kZWQgdHJhbnNpdGlvbiI+CiAgICAgICAgICAgICAgRG93bmxvYWQgUERGCiAgICAgICAgICAgIDwvYT4KICAgICAgICAgICAgPGEgaHJlZj17Ii9hcGkvcmVwb3J0cy8iICsgaWQgKyAiL2pzb24ifSB0YXJnZXQ9Il9ibGFuayIKICAgICAgICAgICAgICBjbGFzc05hbWU9ImJnLXNsYXRlLTcwMCBob3ZlcjpiZy1zbGF0ZS02MDAgdGV4dC13aGl0ZSB0ZXh0LXNtIHB4LTQgcHktMiByb3VuZGVkIHRyYW5zaXRpb24iPgogICAgICAgICAgICAgIEV4cG9ydCBKU09OCiAgICAgICAgICAgIDwvYT4KICAgICAgICAgIDwvZGl2PgogICAgICAgICl9CiAgICAgIDwvZGl2PgoKICAgICAge1sicXVldWVkIiwicnVubmluZyJdLmluY2x1ZGVzKHNjYW4uc3RhdHVzKSAmJiAoCiAgICAgICAgPGRpdiBjbGFzc05hbWU9ImJnLXNsYXRlLTgwMCByb3VuZGVkLXhsIHAtOCB0ZXh0LWNlbnRlciI+CiAgICAgICAgICA8cCBjbGFzc05hbWU9InRleHQtc2xhdGUtMzAwIHRleHQtbGciPlNjYW5uaW5nIHJlcG9zaXRvcnkuLi48L3A+CiAgICAgICAgICA8cCBjbGFzc05hbWU9InRleHQtc2xhdGUtNTAwIHRleHQtc20gbXQtMiI+UGFnZSBhdXRvLXJlZnJlc2hlcyBldmVyeSAzIHNlY29uZHMuPC9wPgogICAgICAgIDwvZGl2PgogICAgICApfQoKICAgICAge3NjYW4uc3RhdHVzID09PSAiY29tcGxldGVkIiAmJiAoIXNjYW4udnVsbmVyYWJpbGl0aWVzIHx8IHNjYW4udnVsbmVyYWJpbGl0aWVzLmxlbmd0aCA9PT0gMCkgJiYgKAogICAgICAgIDxkaXYgY2xhc3NOYW1lPSJiZy1ncmVlbi05MDAvMzAgYm9yZGVyIGJvcmRlci1ncmVlbi01MDAgcm91bmRlZC14bCBwLTggdGV4dC1jZW50ZXIiPgogICAgICAgICAgPHAgY2xhc3NOYW1lPSJ0ZXh0LWdyZWVuLTQwMCB0ZXh0LXhsIGZvbnQtYm9sZCI+Tm8gdnVsbmVyYWJpbGl0aWVzIGRldGVjdGVkITwvcD4KICAgICAgICA8L2Rpdj4KICAgICAgKX0KCiAgICAgIHtzY2FuLnN0YXR1cyA9PT0gImNvbXBsZXRlZCIgJiYgc2Nhbi52dWxuZXJhYmlsaXRpZXM/Lmxlbmd0aCA+IDAgJiYgKAogICAgICAgIDxkaXY+CiAgICAgICAgICA8aDIgY2xhc3NOYW1lPSJ0ZXh0LXhsIGZvbnQtYm9sZCB0ZXh0LXdoaXRlIG1iLTQiPlZ1bG5lcmFiaWxpdGllcyAoe3NjYW4udnVsbmVyYWJpbGl0aWVzLmxlbmd0aH0pPC9oMj4KICAgICAgICAgIHtbIkNyaXRpY2FsIiwiSGlnaCIsIk1lZGl1bSIsIkxvdyJdLm1hcChzZXYgPT4gewogICAgICAgICAgICBjb25zdCBpdGVtcyA9IHNjYW4udnVsbmVyYWJpbGl0aWVzLmZpbHRlcih2ID0+IHYuc2V2ZXJpdHkgPT09IHNldik7CiAgICAgICAgICAgIGlmICghaXRlbXMubGVuZ3RoKSByZXR1cm4gbnVsbDsKICAgICAgICAgICAgcmV0dXJuICgKICAgICAgICAgICAgICA8ZGl2IGtleT17c2V2fSBjbGFzc05hbWU9Im1iLTYiPgogICAgICAgICAgICAgICAgPGgzIGNsYXNzTmFtZT0idGV4dC1zbGF0ZS00MDAgdGV4dC1zbSBmb250LWJvbGQgdXBwZXJjYXNlIHRyYWNraW5nLXdpZGVyIG1iLTIiPntzZXZ9PC9oMz4KICAgICAgICAgICAgICAgIHtpdGVtcy5tYXAodiA9PiA8VnVsbkNhcmQga2V5PXt2LmlkfSB2dWxuPXt2fSAvPil9CiAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICk7CiAgICAgICAgICB9KX0KICAgICAgICA8L2Rpdj4KICAgICAgKX0KCiAgICAgIHtzY2FuLnN0YXR1cyA9PT0gImZhaWxlZCIgJiYgKAogICAgICAgIDxkaXYgY2xhc3NOYW1lPSJiZy1yZWQtOTAwLzMwIGJvcmRlciBib3JkZXItcmVkLTUwMCByb3VuZGVkLXhsIHAtNiB0ZXh0LWNlbnRlciI+CiAgICAgICAgICA8cCBjbGFzc05hbWU9InRleHQtcmVkLTQwMCBmb250LWJvbGQiPlNjYW4gZmFpbGVkLjwvcD4KICAgICAgICAgIDxwIGNsYXNzTmFtZT0idGV4dC1zbGF0ZS00MDAgbXQtMiI+Q2hlY2sgdGhhdCB0aGUgcmVwb3NpdG9yeSBVUkwgaXMgdmFsaWQgYW5kIHB1YmxpY2x5IGFjY2Vzc2libGUuPC9wPgogICAgICAgIDwvZGl2PgogICAgICApfQogICAgPC9kaXY+CiAgKTsKfQo="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/frontend/src/pages/ResultsPage.jsx")),
    [System.Convert]::FromBase64String($b64)
)

# ---- frontend/src/pages/ScanPage.jsx
$b64 = "aW1wb3J0IHsgdXNlU3RhdGUgfSBmcm9tICJyZWFjdCI7CmltcG9ydCB7IHVzZU5hdmlnYXRlIH0gZnJvbSAicmVhY3Qtcm91dGVyLWRvbSI7CmltcG9ydCBhcGkgZnJvbSAiLi4vc2VydmljZXMvYXBpIjsKCmV4cG9ydCBkZWZhdWx0IGZ1bmN0aW9uIFNjYW5QYWdlKCkgewogIGNvbnN0IFtyZXBvVXJsLCBzZXRSZXBvVXJsXSA9IHVzZVN0YXRlKCIiKTsKICBjb25zdCBbbG9hZGluZywgc2V0TG9hZGluZ10gPSB1c2VTdGF0ZShmYWxzZSk7CiAgY29uc3QgW2Vycm9yLCAgIHNldEVycm9yXSAgID0gdXNlU3RhdGUoIiIpOwogIGNvbnN0IG5hdiA9IHVzZU5hdmlnYXRlKCk7CgogIGNvbnN0IHN0YXJ0U2NhbiA9IGFzeW5jICgpID0+IHsKICAgIGlmICghcmVwb1VybC50cmltKCkpIHsgc2V0RXJyb3IoIlBsZWFzZSBlbnRlciBhIHJlcG9zaXRvcnkgVVJMIik7IHJldHVybjsgfQogICAgc2V0TG9hZGluZyh0cnVlKTsgc2V0RXJyb3IoIiIpOwogICAgdHJ5IHsKICAgICAgY29uc3QgcmVzID0gYXdhaXQgYXBpLnBvc3QoIi9zY2FuIiwgeyByZXBvX3VybDogcmVwb1VybCB9KTsKICAgICAgbmF2KCIvcmVzdWx0cy8iICsgcmVzLmRhdGEuaWQpOwogICAgfSBjYXRjaCAoZXJyKSB7CiAgICAgIHNldEVycm9yKGVyci5yZXNwb25zZT8uZGF0YT8uZGV0YWlsIHx8ICJGYWlsZWQgdG8gc3RhcnQgc2NhbiIpOwogICAgfSBmaW5hbGx5IHsKICAgICAgc2V0TG9hZGluZyhmYWxzZSk7CiAgICB9CiAgfTsKCiAgcmV0dXJuICgKICAgIDxkaXYgY2xhc3NOYW1lPSJtYXgtdy0yeGwgbXgtYXV0byBtdC0xNiBweC00Ij4KICAgICAgPGgxIGNsYXNzTmFtZT0idGV4dC0zeGwgZm9udC1ib2xkIHRleHQtd2hpdGUgbWItMiI+TmV3IFNjYW48L2gxPgogICAgICA8cCBjbGFzc05hbWU9InRleHQtc2xhdGUtNDAwIG1iLTgiPkVudGVyIGEgcHVibGljIEdpdEh1YiByZXBvc2l0b3J5IFVSTC48L3A+CiAgICAgIHtlcnJvciAmJiA8ZGl2IGNsYXNzTmFtZT0iYmctcmVkLTkwMC80MCBib3JkZXIgYm9yZGVyLXJlZC01MDAgcm91bmRlZCBwLTMgdGV4dC1yZWQtMzAwIHRleHQtc20gbWItNCI+e2Vycm9yfTwvZGl2Pn0KICAgICAgPGRpdiBjbGFzc05hbWU9ImJnLXNsYXRlLTgwMCByb3VuZGVkLXhsIHAtNiBzcGFjZS15LTQiPgogICAgICAgIDxpbnB1dAogICAgICAgICAgY2xhc3NOYW1lPSJ3LWZ1bGwgYmctc2xhdGUtNzAwIHJvdW5kZWQgcHgtNCBweS0zIHRleHQtd2hpdGUgb3V0bGluZS1ub25lIGZvY3VzOnJpbmctMiBmb2N1czpyaW5nLWN5YW4tNTAwIgogICAgICAgICAgcGxhY2Vob2xkZXI9Imh0dHBzOi8vZ2l0aHViLmNvbS9vd25lci9yZXBvIgogICAgICAgICAgdmFsdWU9e3JlcG9Vcmx9CiAgICAgICAgICBvbkNoYW5nZT17ZSA9PiBzZXRSZXBvVXJsKGUudGFyZ2V0LnZhbHVlKX0KICAgICAgICAgIG9uS2V5RG93bj17ZSA9PiBlLmtleSA9PT0gIkVudGVyIiAmJiBzdGFydFNjYW4oKX0KICAgICAgICAvPgogICAgICAgIDxidXR0b24KICAgICAgICAgIG9uQ2xpY2s9e3N0YXJ0U2Nhbn0KICAgICAgICAgIGRpc2FibGVkPXtsb2FkaW5nfQogICAgICAgICAgY2xhc3NOYW1lPSJ3LWZ1bGwgYmctY3lhbi02MDAgaG92ZXI6YmctY3lhbi01MDAgZGlzYWJsZWQ6Ymctc2xhdGUtNjAwIHRleHQtd2hpdGUgZm9udC1ib2xkIHB5LTMgcm91bmRlZC1sZyB0cmFuc2l0aW9uIgogICAgICAgID4KICAgICAgICAgIHtsb2FkaW5nID8gIlF1ZXVpbmcgc2Nhbi4uLiIgOiAiU3RhcnQgU2NhbiJ9CiAgICAgICAgPC9idXR0b24+CiAgICAgIDwvZGl2PgogICAgPC9kaXY+CiAgKTsKfQo="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/frontend/src/pages/ScanPage.jsx")),
    [System.Convert]::FromBase64String($b64)
)

# ---- frontend/src/services/api.js
$b64 = "aW1wb3J0IGF4aW9zIGZyb20gImF4aW9zIjsKCmNvbnN0IGFwaSA9IGF4aW9zLmNyZWF0ZSh7IGJhc2VVUkw6ICIvYXBpIiB9KTsKCmFwaS5pbnRlcmNlcHRvcnMucmVxdWVzdC51c2UoKGNmZykgPT4gewogIGNvbnN0IHRva2VuID0gbG9jYWxTdG9yYWdlLmdldEl0ZW0oInRva2VuIik7CiAgaWYgKHRva2VuKSBjZmcuaGVhZGVycy5BdXRob3JpemF0aW9uID0gYEJlYXJlciAke3Rva2VufWA7CiAgcmV0dXJuIGNmZzsKfSk7CgpleHBvcnQgZGVmYXVsdCBhcGk7Cg=="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/frontend/src/services/api.js")),
    [System.Convert]::FromBase64String($b64)
)

# ---- frontend/tailwind.config.js
$b64 = "ZXhwb3J0IGRlZmF1bHQgewogIGNvbnRlbnQ6IFsiLi9pbmRleC5odG1sIiwgIi4vc3JjLyoqLyoue2pzLGpzeH0iXSwKICB0aGVtZTogeyBleHRlbmQ6IHt9IH0sCiAgcGx1Z2luczogW10sCn07Cg=="
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/frontend/tailwind.config.js")),
    [System.Convert]::FromBase64String($b64)
)

# ---- frontend/vite.config.js
$b64 = "aW1wb3J0IHsgZGVmaW5lQ29uZmlnIH0gZnJvbSAidml0ZSI7CmltcG9ydCByZWFjdCBmcm9tICJAdml0ZWpzL3BsdWdpbi1yZWFjdCI7CgpleHBvcnQgZGVmYXVsdCBkZWZpbmVDb25maWcoewogIHBsdWdpbnM6IFtyZWFjdCgpXSwKICBzZXJ2ZXI6IHsKICAgIGhvc3Q6ICIwLjAuMC4wIiwKICAgIHBvcnQ6IDUxNzMsCiAgICBwcm94eTogewogICAgICAiL2FwaSI6IHsKICAgICAgICB0YXJnZXQ6ICJodHRwOi8vYmFja2VuZDo4MDAwIiwKICAgICAgICBjaGFuZ2VPcmlnaW46IHRydWUsCiAgICAgICAgcmV3cml0ZTogKHBhdGgpID0+IHBhdGgucmVwbGFjZSgvXlwvYXBpLywgIiIpLAogICAgICB9LAogICAgfSwKICB9LAp9KTsK"
[System.IO.File]::WriteAllBytes(
    (Join-Path $PWD ($root + "/frontend/vite.config.js")),
    [System.Convert]::FromBase64String($b64)
)

Write-Host ""
Write-Host "All files created!" -ForegroundColor Green
Write-Host ""
Write-Host "NEXT STEPS:" -ForegroundColor Yellow
Write-Host "  1. Edit ai-static-scanner/backend/.env"
Write-Host "     Add: OPENAI_API_KEY=sk-...  or  ANTHROPIC_API_KEY=sk-ant-..."
Write-Host ""
Write-Host "  2. cd ai-static-scanner"
Write-Host "     docker compose up --build"
Write-Host ""
Write-Host "  3. Frontend: http://localhost:3000" -ForegroundColor Cyan
Write-Host "     API Docs:  http://localhost:8000/docs" -ForegroundColor Cyan
Write-Host ""
$ans = Read-Host "Launch docker compose now? (y/n)"
if ($ans -eq "y") {
    Set-Location "$root"
    docker compose up --build
}